### ISSUE TITLE
Tratar item "0 à 0" nas legendas [Ideia: #70]

### ISSUE THREAD

**Issue by rodmaia2099** [lappis-unb/PromovaCultura#103]
>[Ideia: #70]

No componente de legenda:
- [x] Tratar o caso de não ter nenhum dado para mostrar
- [x] Esconder o primeiro item que mostra uma escala de "0 a 0" quando existem dados para mostrar

**Comment by marcosronaldo** [comment]
Trabalho adicional feito nas legendas:
* Identificação do valor 0 em todas as legendas; 
* Alteração de valores para evitar ambiguidade. Exemplo: 0, 0 a 20, 20 a 50 foi transformado em 0, 1 a 20, 21 a 50
