### ISSUE TITLE
Testar formas melhores de evitar sobreposição dos pins no mapa

### ISSUE THREAD

**Issue by rodmaia2099** [lappis-unb/PromovaCultura#106]
Os pins de proponente e incentivador se sobrepõe e são difíceis de identificar nas UFs menores.
Testar alternativas de posicionamento (somente visual).

**Comment by AniaGomes** [comment]
![image](https://user-images.githubusercontent.com/40863789/47977248-254c1d80-e09e-11e8-8a15-9736ae51d72e.png)
![image](https://user-images.githubusercontent.com/40863789/47978071-c2a95080-e0a2-11e8-8572-2611888425b6.png)

**Comment by rodmaia2099** [comment]
Alternativas geradas até o final da sprint não resolvem 100% o problema. Precisamos gerar outras alternativas ou aprofundar mais o estudo.

**Comment by AniaGomes** [comment]
![image](https://user-images.githubusercontent.com/40863789/48022119-76512580-e121-11e8-84c8-f2b96a9f9e7c.png)

**Comment by rodmaia2099** [comment]
Essa versão é uma boa evolução comparada com os círculos brancos, mas o tamanho do círculo está encobrindo parte do mapa, o que não acontecia nessa mesma intensidade antes.
Será que posicioná-los mais no limite externo dos estados não funcionaria melhor? Especialmente os estados do nordeste?
Outro ponto é que a cor de fundo dos pins está se sobressaindo aos ícones. À primeira vista, no exemplo da imagem, a concentração de patrocinadores parece a mesma em todos os estados. Leva alguns segundos para ver que os ícones são diferentes. Precisamos resolver isso também. Será que valeria à pena ter só 1 ícone para patrocinador e variar a cor de fundo do pin?

**Comment by AniaGomes** [comment]
![image](https://user-images.githubusercontent.com/40863789/48154082-eb059a80-e2ae-11e8-91fe-8ece9df4bc8e.png)
![image](https://user-images.githubusercontent.com/40863789/48154125-feb10100-e2ae-11e8-9301-b249f0df218e.png)

Acho que deveríamos mudar as cores dos ícones dos incentivadores já que amarelo é muito difícil de trabalhar. E quanto à organização dos ícones no nordeste, não sei se tem como colocá-los mais no limite externos sem que eles se choquem uns com os outros.

**Comment by AniaGomes** [comment]
Testes de posicionamento
![image](https://user-images.githubusercontent.com/40863789/48352210-58307b80-e673-11e8-9d3c-0393ecb995a0.png)

**Comment by AniaGomes** [comment]
Versão final, com posições e mudança das cores dos ícones dos proponentes (sabendo que os ícones dos incentivadores serão redesenhados)

![mapa_icones](https://user-images.githubusercontent.com/40863789/48368393-bde42e00-e69a-11e8-8239-050b8efa5eb9.PNG)
