### ISSUE TITLE
Verificar problemas do repositório do git

### ISSUE THREAD

**Issue by FranciscoSMM** [lappis-unb/PromovaCultura#119]
Arquivos não estão podendo ser ignorados, mas não fazem parte de modificações e impedem que arquivos sejam pushados e commitados. Problema acontece para Francisco e para Rodrigo.

![image.png](https://images.zenhubusercontent.com/5afd82f34b5806bc2bd38ebf/3b9aa217-038e-4faa-8260-3cb5d196ad6f)

**Comment by joaaogui** [comment]
O diretório node_modules dentor da pasta gh-pages foi removido, e o problema solucionado
