### ISSUE TITLE
Otimizar os SVGs do mapa e pins

### ISSUE THREAD

**Issue by FranciscoSMM** [lappis-unb/PromovaCultura#120]
Otimizar o código dos svgs para diminuir o tamanho deles.

* [ ] Reduzir o tamanho em bytes do Mapa por UF 
* [ ] Reduzir o tamanho em bytes do Mapa por Região 
* [ ] Reduzir o tamanho em bytes dos Pins

### Critérios de Aceitação:
* [ ] Os arquivos estão menores (em bytes)
* [ ] **Teste manual** realizado em todos os protótipos de mapas (testei que funciona e não quebrou nada do que já estava feito)
* [ ] Arquivos **commitados na master**

**Comment by marcosronaldo** [comment]
Otimizar os próprios paths dos caminho do mapa, por exemplo reduzindo precisão dos decimais, ou removendo pontos. Além de tags css e o que mais puder limpar entro dos arquivos svg e também dos paths dentro do prorio JS dos mapas por estado e por região.
