### ISSUE TITLE
Desenhar pop-up com detalhes para desktop [Ideia: #70]

### ISSUE THREAD

**Issue by rodmaia2099** [lappis-unb/PromovaCultura#128]
[Ideia: #70]

Desenhar o pop-up com detalhes de uma UF (ou região) com base nas alternativas geradas em #70. **Somente para Desktop**.

* [x] Gerar versão por UF só com detalhes de proposta
* [x] Gerar versão por UF com detalhes de proposta e combinações de proponente e incentivador
* [x] Gerar versão por região só com detalhes de proposta
* [x] Gerar versão por região com detalhes de proposta e combinações de proponente e incentivador

------

## Critérios de aceitação

* [x] Discuti as versões criadas com a equipe.
* [x] Documentei as **imagens das  versões** em um comentário na issue.
* [x] Documentei as **exceções aos objetivos** da issue ou aos critérios de aceitação em um **comentário na issue**.
* [x] Documentei **todos os bugs** encontrados em novas issues, explicando o problema e os passos para reproduzir.

**Comment by AniaGomes** [comment]
[pop_up_2307.zip](https://github.com/lappis-unb/PromovaCultura/files/2219087/pop_up_2307.zip)
arquivos editáveis das alternativas dos pop ups.
![image](https://user-images.githubusercontent.com/40863789/43074237-fb5f3d4c-8e52-11e8-8c62-d7fb6c63a0c6.png)
![image](https://user-images.githubusercontent.com/40863789/43074301-2b14e1ae-8e53-11e8-97a1-830d0a0a06f4.png)

**Comment by AniaGomes** [comment]
![image](https://user-images.githubusercontent.com/40863789/43135981-965620de-8f1d-11e8-8661-b37c9ea52c56.png)
![image](https://user-images.githubusercontent.com/40863789/43136007-b460253e-8f1d-11e8-82a2-05850ae8404b.png)
![image](https://user-images.githubusercontent.com/40863789/43136032-ce9cb296-8f1d-11e8-9392-db21e3862943.png)

**Comment by AniaGomes** [comment]
ícones com borda - [Ícones.zip](https://github.com/lappis-unb/PromovaCultura/files/2227863/Icones.zip)
