### ISSUE TITLE
Pesquisa de bibliotecas de mapas de software livre

### ISSUE THREAD

**Issue by marcosronaldo** [lappis-unb/PromovaCultura#13]
Possíveis candidatos:
* http://polymaps.org/
* https://rawgit.com/neveldo/jQuery-Mapael/master/examples/advanced/dataviz_example.html
* https://d3js.org/
* http://kartograph.org/
* http://leafletjs.com/examples/choropleth/
* https://www.hongkiat.com/blog/java-libraries-for-interactive-maps/
* http://timeline.knightlab.com/#examples
* http://techslides.com/50-java-libraries-and-plugins-for-maps
* https://www.amcharts.com/demos/
* https://www.sitepoint.com/15-best-java-charting-libraries/
* http://datamaps.github.io/
* https://codepen.io/fabiogoodoy/pen/wgipx
* http://vitroz.github.io/MapaInterativoJS/
* http://maujorsvg.com.br/mapabrasil/
* https://www.amcharts.com/demos/

**Comment by navarrovmn** [comment]
* [Chart.JS](https://www.chartjs.org/)
* [Google Charts (Creative Commons)](https://developers.google.com/chart/interactive/docs/gallery/geochart)
* [Chartkick](https://www.chartkick.com/)

**Comment by peterlima** [comment]
Pesquisa sendo documentada na página: [wiki biblioteca de mapas](https://github.com/lappis-unb/PromovaCultura/wiki/An%C3%A1lise-de-biblioteca-de-mapas)
