### ISSUE TITLE
 Implementar pop-up com detalhes para desktop [Ideia: #70] 

### ISSUE THREAD

**Issue by marcosronaldo** [lappis-unb/PromovaCultura#133]
Implementar versões de pop-up com detalhes de uma UF (ou região) com base nas alternativas geradas em #128. Somente para Desktop.
* [x] Remover referencia ao componente novo (incompleto) dos layouts do mapa;
* [x] Corrigir proporção do popup em relação ao mapa;
* [x] Abrir o popover com click ou hover em um estado/UF;
* [x] Utilizar dados reais da API para popular o popover;
* [ ] Ajustar posicionamento do popover com a seta que aponta para o estado clicado;
* [x] Esconder os números de proponentes e incentivadores quando o filtro não estiver ativo;
* [ ] Estudar vantagem entre mostrar popover apontando para o estado e uma janela com botão de fechar;

**Comment by marcosronaldo** [comment]
Issue em andamento na branch balloon_info

**Comment by marcosronaldo** [comment]
TODO: 
* Remover referencia ao componente novo (incompleto) dos layouts do mapa.
* Abrir o popover com o click em um estado/UF;
* Utilizar dados reais da API para popular o popover;
* Ajustar posicionamento do popover com a seta que aponta para o estado clicado;

**Comment by marcosronaldo** [comment]
Observações
* A informação do segmento mais relevante do estado não está sendo carregada da API, está com valor fixo.
* Decidimos remover a seta para ficar 'menos poluído', e a função de indicar o estado que está 'aberto' é feita por uma cor diferente no estado.

**Comment by fabio1079** [comment]
__Sobre__: Ativar os proponentes/incentivadores com cartão ativo, o card fica com valor correspondente 0, só recarrega quando passa no mapa.
Pensando agora, os dados do cartão são alterados via "emit", que neste caso é executado quando o usuário passa o mouse sobre o mapa(ou clica em um estado). Para atualizar os dados do cartão com ele aberto quando o usuário ativar proponentes/incentivadores é só disparar o mesmo "emit" com os dados esperados por ele.
EX:
```javascript
let data = {abbreviation: "DF", name: "Distrito Federal"};
eventBus.$emit('mapOnMouseOver', data);
```
Ele recebe da API como prop do seu component pai: projects, proponents, incentivators e usa "abbreviation" para filtrar os valores do card.
