### ISSUE TITLE
Prototipar animações e efeitos visuais [Ideia #72]

### ISSUE THREAD

**Issue by rodmaia2099** [lappis-unb/PromovaCultura#136]
* [x] Prototipar 3 alternativas de efeitos visuais
* [x] Testar bibliotecas de animação mais promissoras
* [x] Implementar 3 provas de conceito dos protótipos usando uma ou mais bibliotecas
* [x] Fazer ajustes na API para buscar dados relacionados as ideias acima, se necessário
* [x] Verificar possibilidade de adicionar alguma informação adicional na API salic que possa agregar valor no produto;
* [x] Identificar filtros pertinentes para cada uma das visualizações;

### Critérios de aceitação

* [x] Responsivo
* [x] Performance
* [x] Todas as formas de visualização precisam utilizar dados reais ou dados mock para mostrar de forma clara a proposta.
* [x] Todas as formas de visualização precisam entregar valor para o MinC, não pode ser só "bonitinho".
* [x] A equipe inteira deve estar consciente das propostas sendo implementadas, ou seja, o que ela agrega de valor.

**Comment by joaaogui** [comment]
Em relação ao grafo:

Branch: **graph**
File: gh-pages/graph.html

Para popular o grafo, abrir o console do browser e rodar getLinks()

**Comment by joaaogui** [comment]
Sunburst:

* Trocar biblioteca para o echarts, com o objetivo de utilizar somente uma biblioteca.
* Tamanho do sunburst, pode diminuir, principalmente a área central
* Para continuar com visualização de sunburst, é indispensável ter a visualização de segmentos.
* Não funciona mostrar a diferença entre range de anos, mudar para uma visualização do sunburst para cada ano

**Comment by marcosronaldo** [comment]
Terceira ideia em #155
