### ISSUE TITLE
Definir framework de front end

### ISSUE THREAD

**Issue by marcosronaldo** [lappis-unb/PromovaCultura#14]
Candidatos:
* Polymer
* VueJS
* React
* Stencil
outros

**Comment by rodmaia2099** [comment]
Vamos definir um framework de antemão e fazer toda a nossa exploração na prototipagem se encaixar nesse framework? Ou exploramos todas as nossas ideias livremente e escolhemos um framework que dê a maior (e mais fácil) cobertura a todos os protótipos que vamos escolher no final?
Justifique sua resposta :P

**Comment by marcosronaldo** [comment]
Esse problema não será tratado nessa etapa do projeto.
