### ISSUE TITLE
Gráfico de sun burst com quantidade de projetos por segmento e filtro de ano

### ISSUE THREAD

**Issue by marcosronaldo** [lappis-unb/PromovaCultura#142]
* [x] Mostrar segmentos e verificar a mutabilidade das informações por ano;
* [x] Trocar biblioteca para o echarts, com o objetivo de utilizar somente uma biblioteca; ( #144 )
* [x] Tamanho do gráfico pode diminuir, principalmente a área central;
* [x] Mudar para uma visualização do sunburst para cada ano, já que o range de 2 anos não funciona.
* [x] Testar gradiente de cores. Testar variação HSL;

------

## Critérios de aceitação
* [x] As áreas e segmentos podem ser diferenciados um dos outros;
* [x] As informações de segmentos e áreas mostradas no gráfico podem ser filtradas por ano;
* [ ] O tamanho do gráfico está responsivo;
* [x] Os segmentos e áreas podem ter seus valores absolutos informados no gráfico;
* [ ] **Teste manual** realizado (testei que funciona e não quebrou nada do que já estava feito)
* [ ] Confirmei que o **Merge request** foi revisado e aceito por uma pessoa que não estava envolvida na issue
* [x] Documentei as **exceções aos objetivos** da issue ou aos critérios de aceitação em um **comentário na issue**.
* [x] Documentei **todos os bugs** encontrados em novas issues, explicando o problema e os passos para reproduzir.

**Comment by peterlima** [comment]
Novas tasks:

[] Criar legenda das Áreas fora do gráfico;
[] Diagramar página que composta pelo gráfico, legenda e slider;

**Comment by FranciscoSMM** [comment]
Ao ver que o gráfico Sunburst daria muitos problemas e não resolveria o problema do jeito que nós havíamos pensado e com o fator de estarmos mudando para a biblioteca do E-Charts, resolvemos usar outro tipo de gráfico para tentar resolver a visualização de informação dos projetos/ano. 
O Nested pies, acabou sendo uma opção boa. Algo que notamos também era que as áreas possuíam pouca variação durantes os anos e isso justificaria uma abordagem mais estática para essa informação.
![b7c2e187](https://user-images.githubusercontent.com/38992510/44659216-d9179980-a9d9-11e8-9643-d056b011d6f0.png)

**Comment by FranciscoSMM** [comment]
Fizemos então um mockup para definir algumas cores e etética para a visualização final do gráfico.

![image](https://user-images.githubusercontent.com/38992510/44659889-28f76000-a9dc-11e8-957c-1985df718623.png)

**Comment by FranciscoSMM** [comment]
![image](https://user-images.githubusercontent.com/38992510/44660355-bd15f700-a9dd-11e8-9baf-bef41534a92b.png)

**Comment by marcosronaldo** [comment]
* [ ] Mudar comportamento do cursor no círculo de segmentos, pois não há interação.

**Comment by marcosronaldo** [comment]
Continuação do trabalho dessa issue em #152
