### ISSUE TITLE
Grafo de deslocamentos

### ISSUE THREAD

**Issue by marcosronaldo** [lappis-unb/PromovaCultura#143]
* [x] Implementar proporção do tamanho de cada círculo; 
* [x] Documentar opções exploradas dos tamanhos dos círculos;
* [x] Tooltips do tamanho do círculo e da ligação deve conter as informações relativas ao que foi clicado; 
* [x] Trocar nomes por extenso por abreviações de cada UF;
* [x] Trocar estratégia que determina a largura de cada linha;
* [x] Testar posicionamento fixo, ou aumentar distancia entre as bolinhas para reduzir a mancha visual;
* [x] Testar gradiente de cor nas ligações e testar ausência da ligação quando fora de foco;

------

## Critérios de aceitação
* [x]  Os círculos estão com tamanho visível que pode ser facilmente diferenciado dos demais.
* [x] Está claro o que os círculos e as ligações representam no grafo;
* [x] Cada círculo está com UF legível e identificável sem sair do circulo;
* [x] As linhas com valores bem distantes estão visivelmente distintas umas das outras;
* [x] **Teste manual** realizado (testei que funciona e não quebrou nada do que já estava feito)
* [x] Confirmei que o **Merge request** foi revisado e aceito por uma pessoa que não estava envolvida na issue
* [x] Documentei as **exceções aos objetivos** da issue ou aos critérios de aceitação em um **comentário na issue**.
* [x] Documentei **todos os bugs** encontrados em novas issues, explicando o problema e os passos para reproduzir.

**Comment by FranciscoSMM** [comment]
Primeiro teste de vizualização dos grafos por posição fixa no canvas.

![grafos_fixos_1](https://user-images.githubusercontent.com/38992510/44166309-781ac800-a0a1-11e8-81bb-376d000b4726.PNG)

**Comment by FranciscoSMM** [comment]
Segunda tentativa de criação da posição dos grafos, as posições foram mudadas para ficarem de acordo com a disposição no gráfico cartesiano.

![grafos_fixos_2](https://user-images.githubusercontent.com/38992510/44168089-6ab40c80-a0a6-11e8-8b44-eeb65c88ce5c.PNG)

**Comment by joaaogui** [comment]
Novas tasks:
* [x] Adicionar loading até o grafo ser carregado completamente
* [x] Dispor nome completo da região na legenda 
* [ ] Manter estado selecionado quando o mesmo for clicado

**Comment by joaaogui** [comment]
Decisões tomadas: 
* Não foi ultilizada a variação de cores nas linhas, já que sem a variação a visualização ficou mais limpa e mais direta.
* No primeiro momento do carregamento do grafo, a cor das ligações foi "enfraquecida", já que não existia muita informação a ser retirada dessa visualização, e deixava o visual do grafo poluido.
* A pequena animação existente no momento do hover dos circulos foi retirada, afim de deixar menos poluida a interação com o grafo

**Comment by marcosronaldo** [comment]
* [ ] Colocar tooltips no singular, assim como nas legendas.

**Comment by marcosronaldo** [comment]
BUG: De vez em quando o hover no estado de SP não destaca as ligações.

**Comment by joaaogui** [comment]
A proporção do tamanho dos circulos e das linhas foi feita sem um estudo mais a fundo sobre os dados. Deve ser feito tal estudo.
