### ISSUE TITLE
Melhorias  gráfico Nested Pie de quantidade de projetos

### ISSUE THREAD

**Issue by marcosronaldo** [lappis-unb/PromovaCultura#152]
* [x] Analisar comportamento do cursor no círculo de segmentos, pois não há interação.
* [x] Definir cor fixa com contraste suficiente para os labels dos segmentos.
* [x] Resolver erros de renderização das cores em HSL.
* [x] Incluir a fatia "outros" no gradiente de cores; (testar em cinza ou dentro do gradiente)
* [x] Posicionar a legenda alinhada horizontalmente e abaixo do gráfico;
* [x] Formatar slider de anos para o retratado na issue #142.
* [x] Diagramar página que contempla os elementos do gráfico nested pie, com legenda e slider.

------

## Critérios de aceitação (baseados em #142)
* [x] As áreas e segmentos podem ser identificados e diferenciados um dos outros;
* [x] Está claro no gráfico a área dos segmentos sendo mostrados;
* [ ] As informações de segmentos e áreas mostradas no gráfico podem ser filtradas por ano;
* [ ] A página do gráfico está responsiva;
* [x] Os segmentos e áreas podem ter seus valores absolutos informados no gráfico;
* [x] **Teste manual** realizado (testei que funciona e não quebrou nada do que já estava feito)
* [x] Confirmei que o **Merge request** foi revisado e aceito por uma pessoa que não estava envolvida na issue
* [x] Documentei as **exceções aos objetivos** da issue ou aos critérios de aceitação em um **comentário na issue**.
* [x] Documentei **todos os bugs** encontrados em novas issues, explicando o problema e os passos para reproduzir.

**Comment by AniaGomes** [comment]
Com os objetos agora centralizados no canvas, os nomes dos segmentos ficam para o lado de fora do gráfico de doughnut. Poucas mudanças foram feitas da ultima issue para essa, mas as tarefas que ficaram, como a de formatar o slider e arrumar as cores, foram feitas.

**Comment by peterlima** [comment]
As legendas de segmentos que ficam externas ao gráfico estão cortando na versão mobile.
Serão necessário novos estudos para decidir sobre a viabilidade de ajustes diretamente na biblioteca do gráfico.

**Comment by marcosronaldo** [comment]
* [ ] Atualizar gráfico com click no slider, não apenas com drag;

**Comment by marcosronaldo** [comment]
BUG:
Dar um zoom na página e no gráfico pode acarretar em todos os nós do grafo ficarem sobrepostos;
