### ISSUE TITLE
Definir instrução de uso do protótipo novo

### ISSUE THREAD

**Issue by marcosronaldo** [lappis-unb/PromovaCultura#154]
* [x] Definir instruções textuais de uso das funcionalidades do protótipo #155;

------

## Critérios de aceitação
* [x] A instrução pode ser facilmente identificada pelo usuário.
* [x] Essa ajuda pode ser revisitada pelo usuário caso ele assim deseje;
* [x] A solução de ajuda/guia de uso pode ser aplicada em outros protótipos;
* [x] **Teste manual** realizado (testei que funciona e não quebrou nada do que já estava feito)
* [x] Confirmei que o **Merge request** foi revisado e aceito por uma pessoa que não estava envolvida na issue
* [x] Documentei as **exceções aos objetivos** da issue ou aos critérios de aceitação em um **comentário na issue**.
* [x] Documentei **todos os bugs** encontrados em novas issues, explicando o problema e os passos para reproduzir.

Não se aplica à essa issue:
* [ ] Todas as interações possíveis com o protótipo estão claras e devidamente explanadas;
* [ ] Existem links para explicações e auxílio externo, caso aplicável;
* [ ] A solução de ajuda foi testada por pessoa(s) externa(s) à equipe do promova cultura na versão mobile;
* [ ] A solução de ajuda foi testada por pessoa(s) externa(s) à equipe do promova cultura na versão desktop;

**Comment by AniaGomes** [comment]
![image](https://user-images.githubusercontent.com/40863789/45111176-ab89c900-b11a-11e8-9314-be033e11bd38.png)
![image](https://user-images.githubusercontent.com/40863789/45111186-b2184080-b11a-11e8-9a9c-429c1c098555.png)

**Comment by AniaGomes** [comment]
Fizemos testes para a visualização das instruções das páginas com um link que seria fixado no início de cada página e, quando clicado, abriria uma modal com todas as instruções. Durante a sprint tivemos mais algumas ideias de visualização porém não tivemos tempo de testar todas. Uma das ideias que não testamos era a de fazer o link da instrução de uso como uma orelha do lado direito da página, a fim de não atrapalhar os outros elementos.

**Comment by joaaogui** [comment]
Link para acesso: 

**http://guia.surge.sh/**

**Comment by marcosronaldo** [comment]
* [ ] Criar forma de mini tutorial para que todas as interações possíveis com o protótipo estejam claras e devidamente explanadas; Podem existem links para explicações e auxílio externo, caso aplicável;

**Comment by FranciscoSMM** [comment]
texto com as instruções das páginas do git hub pages
[texto dos tutoriais.txt](https://github.com/lappis-unb/PromovaCultura/files/2398564/texto.dos.tutoriais.txt)
