### ISSUE TITLE
Corrigir certificado da API salic no lappis

### ISSUE THREAD

**Issue by marcosronaldo** [lappis-unb/PromovaCultura#159]
Corrigir certificado da API salic na infra lappis, para abrir os protótipos que usam a API sem precisar avisar o navegador para ignorar aviso de segurança.

**Comment by guilacerda** [comment]
A api agora está com certificado válido. Quando entra no site mostra como não totalmente seguro por causa de uma imagem que está sendo utilizado e ela é http (not safe). Só que não tem diferença para acesso ao graphiql, que é o que importa pra gente.

* Imagem que está sendo requisitada via http
![image](https://user-images.githubusercontent.com/26297247/45430472-c2c93900-b67b-11e8-8dc9-d2409bb65917.png)


Novo link: https://salicapi.lappis.rocks
