### ISSUE TITLE
Implementar a ilustração mapa do Brasil 

### ISSUE THREAD

**Issue by eduardonunes2525** [lappis-unb/PromovaCultura#16]
* [x] Mapa do Brasil
  * Estados separados;
  * Regiões Separadas;
* [x] Estados clicáveis para ativar determinada ação
* [x] Colorir Estados individualmente
* [x] Usar ideia visual do card
* [x] Fazer merge para master
* [ ] Documentar soluções na Wiki
* [x] Criar página para github pages

**Comment by rodmaia2099** [comment]
Precisamos chegar ao nível de município. Cabe nessa issue?

**Comment by peterlima** [comment]
Visualização por município dentro do mapa não é viável.
