### ISSUE TITLE
Estudar visualização mobile para as informações de deslocamento 

### ISSUE THREAD

**Issue by joaaogui** [lappis-unb/PromovaCultura#161]
- [x] Definir forma de visualização mobile para as informações utilizadas no grafo de deslocamento

**Comment by AniaGomes** [comment]
![image](https://user-images.githubusercontent.com/40863789/46610656-b2bd4180-cae1-11e8-87ad-3e5258e759a9.png)

**Comment by AniaGomes** [comment]
![image](https://user-images.githubusercontent.com/40863789/46610683-c799d500-cae1-11e8-9810-1ddf4152aad3.png)

**Comment by AniaGomes** [comment]
[mobile_grafo_deslocamento.zip](https://github.com/lappis-unb/PromovaCultura/files/2572058/mobile_grafo_deslocamento.zip)

**Comment by AniaGomes** [comment]
![image](https://user-images.githubusercontent.com/40863789/49035621-7a121e00-f19c-11e8-93b0-aaf689d35fbd.png)

#db3737
#ef6b29
#edcb3b
#3aa53a
#17A984
#1602d3
#416e82
#7f6793
