### ISSUE TITLE
Definir diagramação principal do mapa

### ISSUE THREAD

**Issue by joaaogui** [lappis-unb/PromovaCultura#162]
Existem quatro diagramações na parte principal do gh-pages. Afim de se melhorar a visualização dos protótipos em geral, definir uma diagramação principal e mover as outras para a parte inferior da página.

**Comment by joaaogui** [comment]
Escolhas feitas:

* Desktop:
  - Filtro: colapsável, fechado, deixar mais intuitivo
  - Legenda: Aberta, com abas, aba com indicativo visual de carregamento

* Mobile:
 - Filtro: Icone ao lado do mapa, modal
 - Legenda: Por abas, aberto, aba com indicativo visual de carregamento

**Comment by guilacerda** [comment]
Escolhas finais:

* Desktop:
    *  Filtro: Colapsável mas começa aberto, fica mais intuitivo. Decidido após a criação do protótipo
    * Legenda: Aberta, com abas (todas já clicáveis e inicializadas), se não selecionada no filtro irá apresentar mensagem indicativa

* Mobile:
    * Filtro: Ícone ao lado do mapa, modal
    * Legenda: Abas, aberto, mensagem indicativa de que não está selecionada
