### ISSUE TITLE
Estudar visualização mobile para segmentos e áreas por ano

### ISSUE THREAD

**Issue by marcosronaldo** [lappis-unb/PromovaCultura#163]
* [x] Estudar novas formas de visualizar no mobile a mesma informação que no desktop é mostrada pelo gráfico de nested pie;
* [x] Criar rascunhos de interface baseado no estudo
* [x] Validar dos rascunhos desenvolvidos
* [x] Criar design visual da(s) proposta(s) escolhida(s)

**Comment by FranciscoSMM** [comment]
Rascunho após algumas horas de pesquisa sobre gráficos para mobile. Um dos dois rascunhos trás uma possibilidade de não usar o gráfico em si, mas outra forma de mostrar as áreas e suas porcentágens conforme os anos. Também testei colocando as imagens no celular para ver proporção e espaçoes.
![teste_mobile_5](https://user-images.githubusercontent.com/38992510/45447495-21a3a800-b6a6-11e8-8c04-3216804075a6.png)
![teste_mobile_3](https://user-images.githubusercontent.com/38992510/45447497-21a3a800-b6a6-11e8-91c6-1a2b924e80ee.png)

**Comment by FranciscoSMM** [comment]
No primeiro, cada seção mostra uma porcentagem da quantidade de projetos por ano, e a sanfona revela quais segmentos da área o suas respectivas porcentagens relativas a ela.

No segundo o gráfico fica mais como ilustrativo e as áreas podem ser selecionadas individualmente, revelando seus segmentos e porcentagens referentes.

**Comment by FranciscoSMM** [comment]
Após o feedback, foram criadas mais duas opções. Nelas, legendas indicando a natureza das informações foram colocadas. Além disso, a segunda opção foi modificada para não mostrar uma progressão com a barra, mas utiliza as cores de outra forma, a indicar qual área está.

![teste_mobile_7](https://user-images.githubusercontent.com/38992510/45629226-44e6a280-ba6c-11e8-8675-e1a39754ea5d.png)
![teste_mobile_8](https://user-images.githubusercontent.com/38992510/45629227-44e6a280-ba6c-11e8-8bd3-5113fee3553f.png)

**Comment by FranciscoSMM** [comment]
Depois de um último feedback sobre a versão com o gráfico, algumas informações foram mostradas de uma nova forma. Agora as porcentagens aparecem como uma barram novamente fazendo alusão a um protótipo antigo, uma vez que existe um limite para a quantidade de projetos em cada segmento já que esses remetem a uma área.

![teste_mobile_9](https://user-images.githubusercontent.com/38992510/45640348-c3e9d400-ba88-11e8-9078-bb29cb0c7041.png)

**Comment by FranciscoSMM** [comment]
Arquivo Editavel do Inkscape

[arquivo editavel inkscape.zip](https://github.com/lappis-unb/PromovaCultura/files/2419835/arquivo.editavel.inkscape.zip)
