### ISSUE TITLE
Ajuste fino do protótipo de acessos gratuitos

### ISSUE THREAD

**Issue by marcosronaldo** [lappis-unb/PromovaCultura#167]
* [x] Definir novas cores para o protótipo; 
* [x] Mostrar na página que existem áreas que não possuem projetos gratuitos e consequentemente não são mostradas no gráfico.
* [x] Ajustar o estilo do texto dos cards para ficar mais parecido com o protótipo do mapa;
* [x] Trocar texto da tooltip de % de projetos gratuitos por % de acesso gratuito;
* [x] Testar utilização container fluido para utilizar melhor a área da página;

**Comment by joaaogui** [comment]
Sobre as áreas gratuitas, nessa issue será adicionado uma forma de mostrar que as areas sem nenhuma distribuição gratuita nao estão sendo dispostas no grafo. Porém, é necessário para o futuro, estudar alguma forma, caso se aplique, de mostrar as áreas sem nenhuma distribuição gratuita no grafo.

**Comment by joaaogui** [comment]
OBS: Na tooltip, o texto "acesso gratuito" foi mantido em caixa baixa para evitar poluição visual

**Comment by AniaGomes** [comment]
Testes de cores do grafo
![image](https://user-images.githubusercontent.com/40863789/45626622-56c54700-ba66-11e8-8e3f-6f34736e3247.png)
![image](https://user-images.githubusercontent.com/40863789/45626733-968c2e80-ba66-11e8-8af0-e98f27954e1c.png)
![image](https://user-images.githubusercontent.com/40863789/45627281-00590800-ba68-11e8-8e3c-d8f0ddffd848.png)

**Comment by joaaogui** [comment]
- [ ] Trocar o tooltip das areas para "Acesso gratuito"
