### ISSUE TITLE
Criar filtros de interação com o mapa do Brasil

### ISSUE THREAD

**Issue by eduardonunes2525** [lappis-unb/PromovaCultura#18]
~~* [ ] Definir as possibilidades de filtro para cada variação de mapa. Ex: Por categoria do projeto, área dos incentivadores, filtro por data do projetos, filtro por etapa, por região.~~
* [x] Especificar filtros do protótipo [que bonitas as luzes](#9) 
  * Qualquer exemplo de visualização do resultado do filtro
* [x] Implementar controles para realizar a troca de dados no mapa. 
  * Ex.: prototipo [que bonitas as luzes](#9)
* [x] Avaliar possibilidade de uso da ferramenta surge.sh
* [x] Utilizar dados reais da api salic local do ambiente do lappis

**Comment by rodmaia2099** [comment]
Coloquei um exemplo de formulário com linguagem natural no Surge, só pra demonstrar como funcionaria na prática: http://naturallangform.surge.sh. 
O código que usei como base está disponível aqui: https://tympanus.net/codrops/2013/05/21/natural-language-form-with-custom-input-elements/.

Notem que precisaríamos de um pouco mais de inteligência para fazer a concordância entre certas opções. Para isso, preparei um [mapeamento das opções](https://docs.google.com/spreadsheets/d/1NmNx1CRhIZXJRTdZuJBqi7jBFTBA4Ij9n_mDzAyMWL0/edit?usp=sharing).

**Comment by joaaogui** [comment]
Os filtros de linguagem natural foram adicionados a página. O controle do mapa pode ser feito pelo dropdown de estados.

É possivel interagir com o mapa em: promovacultura.surge.sh

**Comment by joaaogui** [comment]
@rodmaia2099 O input tava com o placeholder invisivel, resolvido.

**Comment by fabio1079** [comment]
A situação do projeto, no banco é um campo de texto livre.
Consegui habilitar uma busca dentro desse texto pela API, buscando pelo texto "arquivado" dentro da situação. Limitando para apenas 10 resultados.
Levou uns 15~20 segundos... :sob: 

Até este momento, uma busca:
"Eu quero ver de onde vieram projetos aceitos de música" pode levar uns 30 segundos.
