### ISSUE TITLE
Consertar funcionamento dos protótipos crossbrowser

### ISSUE THREAD

**Issue by joaaogui** [lappis-unb/PromovaCultura#182]
A priori, o gh pages quebra no ie ~~e no safari~~

- [x] Investigar e documentar o motivo.
- [x] Resolver o problema.

**Comment by peterlima** [comment]
Foi colocado um aviso na pagina quando a mesma é carregada no ie.

Foi descoberto que o problema inicial é uma dependencia, "babel-loader"

**Comment by joaaogui** [comment]
Após alguma investigação posterior, foi descoberto que é necessário adicionar as dependencias a serem transpiladas no arquivo webpack.base.conf.js
`     
 {
        test: /\.js$/,
        loader: 'babel-loader',
        include: [resolve('src'), resolve('test'), resolve('node_modules/webpack-dev-server/client')]
      },
'

**Comment by joaaogui** [comment]
Com o estudo para o crossbrowser, foi visto que existem varias dependencias que nao sao usadas e varios arquivos nao utilizados. Os mesmo estão sendo limpados na branch **clean_packages**

**Comment by rodmaia2099** [comment]
Algumas referências que podem ser úteis:

* https://modernizr.com/
* http://script.aculo.us/
* https://polyfill.io/v2/docs/
* https://github.com/filamentgroup/EnhanceJS

**Comment by joaaogui** [comment]
Após mudar os arquivos do diretório _static/_, os seguintes erros são apresentados: 

**Arquivo:** chartjs-plugin-datalabels.min.js 
**Erro:** Unable to get property 'helpers' of undefined or null reference
