### ISSUE TITLE
Resolver falha de conexão da API

### ISSUE THREAD

**Issue by peterlima** [lappis-unb/PromovaCultura#189]
* [ ] Descobrir/Resolver falha de conexão da API com o banco

**Comment by joaaogui** [comment]
O problema da API foi o fim do período de teste do SQL Server, que estava sendo utilizado para rodar o banco do salic.

A solução foi rodar o banco localmente, na máquina local, e acessar a mesma.

**Comment by rodmaia2099** [comment]
O Joênio está fazendo testes para rodar o SQL Server nativo no Linux com uma licença de "developer". Vamos ficar de olho nisso para fazer a mudança no momento certo.

**Comment by joaaogui** [comment]
A api voltou a ter problemas, após a queda de energia do dia 24/11. Não é possivel, no momento, acessar nenhum endpoint da mesma.

É retornado o seguinte erro (no graphql):

> "message": "(pyodbc.OperationalError) ('08S01', '[08S01] [FreeTDS][SQL Server]Unable to connect: Adaptive Server is unavailable or does not exist (20009) (SQLDriverConnect)') (Background on this error at: http://sqlalche.me/e/e3q8)",

Já foi testado a conexão como banco, a mesma funciona bem, localmente. Os serviçoes no rancher também já foram restartados, sem sucesso.

Talvex o problema seja algo relacionado com a rede de onde se encontra o banco e o servidor.
