### ISSUE TITLE
Plotar geograficamente os dados da API por UF

### ISSUE THREAD

**Issue by eduardonunes2525** [lappis-unb/PromovaCultura#19]
Apresentar de forma visual no mapa os 2 primeiros quadrinhos da ideia:
* Mapa de calor e icones

Por UF:
- [x] Quantidade total de projetos
- [x] Quantidade de projetos de um tipo (com base no filtro de Segmento)
- [x] Quantidade de proponentes (com base no filtro de Segmento)
- [x] Quantidade de incentivadores (com base no filtro de Segmento)

Por região:
- [ ] Quantidade total de projetos
- [ ] Quantidade de projetos de um tipo (com base no filtro de Segmento)
- [ ] Quantidade de proponentes (com base no filtro de Segmento)
- [ ] Quantidade de incentivadores (com base no filtro de Segmento)

**Comment by FranciscoSMM** [comment]
Estou colocando aqui um png com as cores e os assets teoricamente usados para completar essa issue, estarei upando os SVGs mais tarde.
![assets_sprint_8](https://user-images.githubusercontent.com/38992510/40846134-1b4a69c0-658f-11e8-998b-947b0d9cacee.png)

**Comment by FranciscoSMM** [comment]
Tive de colocar os arquivos .SVG em zip para poder mandar pelo github

[Assets_Map.zip](https://github.com/lappis-unb/PromovaCultura/files/2063104/Assets_Map.zip)

**Comment by fabio1079** [comment]
Consegui usar vários ícones no jsMaps, mas usando um ícone para cada projeto não será uma boa ideai.
![eita](https://user-images.githubusercontent.com/4295523/40933708-adcada70-6808-11e8-9ded-3e596c1a5807.png)

Provavelmente vamos ter que usar faixas de valores que representam um ícone e legendas sobre essas  faixas.

**Comment by FranciscoSMM** [comment]
ícones criados para  fazer um mapa por qualidade ao invés de quantidade, ou seja, cada faixa de porcentagem possui um símbolo diferente ao invés de uma quantidade para ele.
[íconessvg.zip](https://github.com/lappis-unb/PromovaCultura/files/2081170/iconessvg.zip)

**Comment by fabio1079** [comment]
Só falta integrar incentivadores agora.

![proponnetes_pins](https://user-images.githubusercontent.com/4295523/41207495-8db7ab34-6ced-11e8-9b08-769f0597f748.png)

**Comment by fabio1079** [comment]
* SVG está sem font

**Comment by rodmaia2099** [comment]
Pendências serão resolvidas em #87

**Comment by FranciscoSMM** [comment]
Pins com o texto convertido

[investidores.zip](https://github.com/lappis-unb/PromovaCultura/files/2090582/investidores.zip)

**Comment by rodmaia2099** [comment]
Comentário do @FranciscoSMM movido para #87
