### ISSUE TITLE
Consertar contrastes da paleta de cores

### ISSUE THREAD

**Issue by peterlima** [lappis-unb/PromovaCultura#192]
* [x] Fazer ajustes finos em relação ao contraste das cores definidas.
* [x] Após ajustes, aplicar cores definidas nos protótipos

**Comment by joaaogui** [comment]
**Cores Definidas**

* Artes Cênicas - hsl(273,18%,49%)
* Audiovisual - hsl(3,70%,59%)
* Música - hsl(30,100%,60%)
* Artes Visuais - hsl(53,89%,62%)
* Patrimônio Cultural - hsl(145,64%,49%)
* Humanidades - hsl(168,75%,42%)
* Artes Integradas - hsl(201,77%,56%)
* Museus e Memória - hsl(201,24%,42%)

**Comment by AniaGomes** [comment]
![image](https://user-images.githubusercontent.com/40863789/46628006-a9989880-cb12-11e8-8ab8-fbbb86341c11.png)

**Comment by joaaogui** [comment]
As cores foram modificadas de acordo com a cartilha de acessibilidade do governo, por tal motivo, as mesmas foram documentadas na issue #193.

PS. No nested pie, o degrade da cor roxa não está bem definido, nao dando para diferencias as cores.

**Comment by joaaogui** [comment]
Adendos a essa issue estão na issue #198
