### ISSUE TITLE
Analisar normas de acessibilidade do governo em relação aos protótipos 

### ISSUE THREAD

**Issue by peterlima** [lappis-unb/PromovaCultura#193]
* [x] Estudar as normas de acessibilidade do governo.
* [x] Relato do estado atual do promova em relação as normas de acessibilidade
* [x] Pontuar melhorias em relação a acessibilidade
* [x] Pontuar tópicos de acessibilidade a serem trabalhados
* [x] Estudar/Escolher ferramentas automatizadas de análise de acessibilidade.

**Comment by peterlima** [comment]
Materiais para estudo:

https://www.governodigital.gov.br/transformacao/cidadania/acessibilidade/emag-modelo-de-acessibilidade-em-governo-eletronico

http://emag.governoeletronico.gov.br

http://www.w3c.br/pub/Materiais/PublicacoesW3C/cartilha-w3cbr-acessibilidade-web-fasciculo-I.html

http://www.bengalalegal.com

**Comment by FranciscoSMM** [comment]
Estarei colocando aqui alguns links do W3C, que falam sobre algumas medidas interessantes de acessibilidade:

Alguns que parecem mais próximos de nós.

Fazer Update Manual.
https://www.w3.org/TR/WCAG20-TECHS/G76.html

Padrões de cores (Já usamos)
https://www.w3.org/TR/WCAG20-TECHS/G111.html

Definir palavras especiais já no texto.
https://www.w3.org/TR/WCAG20-TECHS/G112.html

Usando tags para marcar melhor textos e links específicos.
https://www.w3.org/TR/WCAG20-TECHS/G115.html

Usar de ferramentas validadoras de html, para ajudar a remover ambiguidades.
https://www.w3.org/TR/WCAG20-TECHS/G134.html

Usar de tags para enfatizar
https://www.w3.org/TR/WCAG20-TECHS/G138.html

Ser consistente com labels.
https://www.w3.org/TR/WCAG20-TECHS/G197.html

Usar alternate para áreas de imagens em mapas
https://www.w3.org/TR/WCAG20-TECHS/H24.html

Usar abbr para explicar abreviações como kg, km e tal.
https://www.w3.org/TR/WCAG20-TECHS/H28.html

Alguns que me pareceram mais complexos para o que temos.

Versão Falada do texto.
https://www.w3.org/TR/WCAG20-TECHS/G79.html

**Comment by FranciscoSMM** [comment]
[eMAGv31.pdf](https://github.com/lappis-unb/PromovaCultura/files/2464805/eMAGv31.pdf)

**Comment by FranciscoSMM** [comment]
Ferramenta para analisar contrastes entre cores. O contraste mínimo precisa ser de no mínimo 4,5:1.

https://www.w3.org/TR/WCAG20-TECHS/G18.html

No fim do tópico se encontra para download a ferramenta.

**Comment by AniaGomes** [comment]
Novas cores adaptadas de acordo com a cartilha de acessibilidade do governo
![image](https://user-images.githubusercontent.com/40863789/46951629-ec042d00-d05e-11e8-8698-c17edda6c546.png)

**Comment by FranciscoSMM** [comment]
Sites que proveem análises gratuitas sobre acessibilidade de um site.

https://www.powermapper.com/products/sortsite/checks/accessibility-checks/

https://achecker.ca/checker/index.php#output_div

**Comment by FranciscoSMM** [comment]
De acordo com os estudo e pesquisas feitos, O site tem vários problemas, a maioria na utilização de tags, na não opção para voltar para a página principal e contraste de cores, principalmente textos. Algumas alternativas e soluções foram recomendadas nessa issue.
