### ISSUE TITLE
Pesquisar soluções semelhantes

### ISSUE THREAD

**Issue by rodmaia2099** [lappis-unb/PromovaCultura#2]
Como parte das próximas etapas da nossa design sprint, vamos fazer uma demo session de soluções bacanas para os problemas que identificamos [aqui no mapa de uso](https://github.com/lappis-unb/PromovaCultura/wiki/Design-Sprints-Visualizacao#mapa-de-uso) (circulados em vermelho).
Não precisa ser soluções completas, qualquer coisa que sirva inspiração tá valendo!
Qualquer dúvida, me procurem.

**Comment by RochaCarla** [comment]
Coloquei algumas referências encontradas em:
https://docs.google.com/document/d/1ruX_YJTt7BVVTjrWnMJaqjaonbwHNVoVauEuBXYB2gA/edit?usp=sharing

**Comment by rodmaia2099** [comment]
**Exemplos**

Visualização de projetos detalhados: http://www.imdb.com/title/tt0944947/?ref_=nv_sr_1
Personalização da visualização: https://www.broadway.com/shows/the-lion-king/
Facilitar a compreensão: http://rockinrio.com/rio/pt-BR/line-up/aerosmith
Explicitar o impacto social: https://goldeletra.org.br/como_atuamos.html#programas_projetos-sp
