### ISSUE TITLE
Identificar relatórios do Comparar mais próximas às nossas

### ISSUE THREAD

**Issue by rodmaia2099** [lappis-unb/PromovaCultura#200]
### Descrição
Continuação de #191 

### Tarefas
- [x] Rever [planilha de compilação](https://docs.google.com/spreadsheets/d/1HjrNITQ8EGYVrMCxTMUh14Ogyaxum5WVYP4jVDwki4o/edit#gid=617071560) identificar relatórios mais próximos das visualizações
- [x] Explorar dimensões existentes e verificar a precisão dos dados (ex: projetos aprovados)
- [x] Explorar dimensões faltantes e estimar esforço de inclusão (exs: valor ou ano)
- [x] Documentar resultados na issue

### Critérios de Aceitação
- [x] Sabemos quais são as visualizações que vamos trabalhar primeiro e o esforço (impressão geral) necessário para fazê-lo.

**Comment by guilacerda** [comment]
Status da planilha de **Prioridade Inicial** citada acima.

Foram analisadas três tabelas (Valor, Período e Local):

* **Valor:** Foi identificado que já conseguimos pegar os valores(captado, projeto, proposta, aprova e solicitado) via API, isso supriria quase que pela totalidade as prioridades iniciais voltadas para o contexto do valor. 
  * Os valores colocados em amarelo são correspondentes à valores que não temos ainda em endpoints e que faltam ser analisados no banco de dados. Além disso, não pegamos valores relacionados à faixa de preços(intervalo de valores).
   * Os valores marcados em verde diz respeito à endpoints já identificados na API, que estão prontos para serem utilizados.

* **Período:** Foi analisado o modo como conseguimos pegar os dados referentes à data. Recebemos como retorno o formato "ano-mês-dia". Então acho que conseguimos fazer uma lógica para pegarmos somente ano/mês/ano.
    * Temos 3 prioridades que precisam utilizar valores como mês e dia. Então, como explicado àcima, imagino que seja possível fazer um algoritmo para filtragem. Estão marcados como vermelho porque não fizemos nenhum exemplo para pegar esses dados esperados.
    * As linhas da 13 à 19 estão marcadas como amarelas por problema de interpretação de significados de projetos (pois não é sabido se conseguimos pegar qualquer tipo de projeto ainda) - Porém, caso sejam situações semelhantes com o caso de projetos que já temos, conseguiremos facilmente pegar o Ano do projeto.
    * Ademais, estão explicadas nas células as outras observações.

* **Local:** Conseguimos pegar a localidade tanto de propostas como de projetos.

**Comment by rodmaia2099** [comment]
**Período:** parece que conseguimos apenas data de início e fim previstos para o projeto e não as datas das mudanças de etapa.

No momento não conseguimos saber a etapa em que se encontrar um projeto.
