### ISSUE TITLE
Avaliação heurística de usabilidade dos componentes existentes

### ISSUE THREAD

**Issue by rodmaia2099** [lappis-unb/PromovaCultura#202]
## Tarefas
- [x] Avaliar protótipos existentes de acordo com as [heurísticas do Nielsen](https://www.nngroup.com/articles/ten-usability-heuristics/)
- [x] Gerar relatório com problemas encontrados, gravidade e sugestões de resolução (quando viável)

## Critérios de aceitação
- [x] Conhecemos os problemas de usabilidade dos protótipos
- [x] Conseguimos priorizar os problemas identificados

**Comment by rodmaia2099** [comment]
Referência importante para avaliar a gravidade dos problemas: https://www.nngroup.com/articles/how-to-rate-the-severity-of-usability-problems/

**Comment by FranciscoSMM** [comment]
Estou fazendo as anotações e avaliações nesse arquivo aqui

https://docs.google.com/spreadsheets/d/1YcHfbKnBSV4-8aEc5LjvGVWDLe9Of2VDhWUxALTF3ok/edit?usp=sharing
