### ISSUE TITLE
Traduzir o relatório "Proponente - Captação de recursos por UF" em uma visualização

### ISSUE THREAD

**Issue by rodmaia2099** [lappis-unb/PromovaCultura#209]
Precisamos traduzir o relatório do Comparar encontrado em: `Interessados > Proponente > Proponente - captação de recurso por UF` para uma visualização interativa.

Link: http://sistemas.cultura.gov.br/comparar/salicnet/salicnet.php

**Tarefas:**
- [x] Adaptar o mapa de calor para mostrar as 3 dimensões do relatório: proponentes, valor aprovado e valor captado.
- [x] Gerar e documentar na issue pelo menos 3 alternativas para a exibição de valor aprovado e valor captado. Discutir com a equipe e implementar a alternativa escolhida.
- [x] Usar biblioteca para gerar versão "relatório" em CSV da visualização para exportar.
- [x] Retirar elementos de filtro que não são necessários.

**Critérios de aceitação:**
- [x] A equipe da SEFIC consegue visualizar o mapa e entender as informações.
- [x] A visualização deve funcionar em dispositivos móveis.
- [x] É possível salvar um arquivo CSV com os mesmos dados do mapa.

**Comment by FranciscoSMM** [comment]
Ao testar como poderíamos representar a página para o mapa de calor, trouxe três alternativas que mais serviram como iterações entre a ideia.

**Alternativa1** - Ainda seria tentar colocar os valores no tooltip dentro do mapa. Além disso, modificações nos filtros e cards para que fiquem relacionados ao que se está mostrando.
![alternativa_1](https://user-images.githubusercontent.com/38992510/48019472-ae089f00-e11a-11e8-85be-5b666932908f.PNG)

**Alternativa2 -** Agora a tooltip se torna algo fixo na direita, não atrapalhando a visualização do mapa. Ainda existe muita informação sendo mostrada, apesar de agora já poder comparar com o total.
![alternativa_2](https://user-images.githubusercontent.com/38992510/48019794-6a626500-e11b-11e8-9756-e1e9a096d026.PNG)

**Alternativa3 -** Trazendo um pouco de similaridade com o funil trouxe uma comparação mais direta entre o valor do estado e o valor total. Isso acabou enxugando a informação de forma visual, mas ainda mostrando tudo.
![alternativa_3](https://user-images.githubusercontent.com/38992510/48019935-c88f4800-e11b-11e8-85cf-93ebbcba2809.PNG)

**Comment by FranciscoSMM** [comment]
Ainda é preciso ver como fazer uma forma de comparar mais estados ao mesmo tempo. A inserção de uma tabela abaixo do mapa para uma comparação mais extensa pode ser algo útil para nós, ma vez que seria preciso ainda fazer um jeito de imprimir as informações.

**Comment by FranciscoSMM** [comment]
Após feedback, decidimos fazer a versão mobile mais parecida com o padrão da issue 161, pois esse era seu objetivo. No entanto, adaptamos para que servisse o propósito de valor captado.
![testemobile_2](https://user-images.githubusercontent.com/38992510/48361211-3097de00-e688-11e8-8b69-874ddd327d19.png)

**Comment by joaaogui** [comment]
Existem alguns problemas em relação ao dados da API:

* Não existe um modo efetivo de se recuperar os dados sobre o valor captado e aprovado dos proponentes de cada UF.
* A solução mais próxima, seria utilizar o campo "total_captado" contido no endpoint proponente, porém, o mesmo tem sempre o mesmo valor, para todos os proponentes em todos os estados.

PS: 
* Tentou-se também utilizar os valores captados e aprovados dos projetos de cada estado, porém, analisando o relatório percebeu-se que essa informação não seria a mesma. Além disso, pro algum motivo, não é possível limitar a query do endpoint de projetos para um valor muito alto, afim de se recuperar todos os projetos.

**Comment by FranciscoSMM** [comment]
ícones para o card do mapa.
[iconescard.zip](https://github.com/lappis-unb/PromovaCultura/files/2582021/iconescard.zip)

**Comment by joaaogui** [comment]
Ajustes nos protótipo serão feitos na issue #217
