### ISSUE TITLE
Avaliação heurística de usabilidade dos componentes existentes na versão mobile

### ISSUE THREAD

**Issue by AniaGomes** [lappis-unb/PromovaCultura#210]
## Tarefas
- [x] Avaliar protótipos existentes na versão mobile de acordo com as [heurísticas do Nielsen](https://www.nngroup.com/articles/ten-usability-heuristics/)
- [x] Gerar relatório com problemas encontrados, gravidade e sugestões de resolução (quando viável)

## Critérios de aceitação
- [x] Conhecemos os problemas de usabilidade dos protótipos
- [x] Conseguimos priorizar os problemas identificados

**Comment by rodmaia2099** [comment]
Referência importante para avaliar a gravidade dos problemas: https://www.nngroup.com/articles/how-to-rate-the-severity-of-usability-problems/

**Comment by AniaGomes** [comment]
Tabela com avaliações dos protótipos mobile: https://docs.google.com/spreadsheets/d/1mJhnPSw7OsYzEP9dCqF6le-F2X4G9ZbJwktwS5CYjSQ/edit#gid=0
