### ISSUE TITLE
Ajustes finos no protótipo de mapa do valor captado (Desktop/Mobile)

### ISSUE THREAD

**Issue by joaaogui** [lappis-unb/PromovaCultura#217]
### Description

 O protótipo está definido (#209), porém as duas versões (Desktop/Mobile) ainda necessitam de ajustes. 

#### Desktop
- [x] Mudar o título
- [ ] Refinar o card do hover, baseado em uma nova proposta 
- [x] Redefinir peso do card de total
- [x] Redefinir diagramação e hierarquia dos cards laterais
- [x] Definir posição do botão de csv 
- [x] Implementar loading onde for necessário
- [x] Integrar a legenda dos ícones a legenda de calor, caso seja a melhor solução.
#### Mobile
- [x] Diminuir tamanho do título
- [ ] Redefinir as cores do protótipo todo (Seguindo as cores padrões, issue #192)
- [ ] Estudar necessidade de uma nova legenda para as cores 
- [x] Implementar loading onde for necessário
- [ ] Resolver scroll grudando em alguns navegadores 
- [x] Arrumar posição da seta, quando ela está aberta
- [x] Adicionar barra branca antes da div da seta
- [ ] Adicionar máscara para valores
- [x] Estudar e definir se o total deve estar no final da página ou sempre visivel (Como o sticky-top)
- [x] Fazer redesign das barras de total e legenda de estado e captação

#### Desktop
- [ ] Saber qual o nome do protótipo em questão.
- [ ] Perceber mudança positiva na estética da página e seu fluxo.
- [ ] Saber se a página ainda está carregando

#### Mobile
- [ ] Conseguir distinguir as regiões de cada estado
- [ ] Conseguir comparar os valores de cada estado com o total sempre
- [ ] Ver quantos milhares ou milhões o valor representa exatamente, junto com sua quantidade de centavos
- [ ] Perceber mudança positiva na estética da página e seu fluxo.
- [ ] Saber se a página ainda está carregando

**Comment by FranciscoSMM** [comment]
Aparentemente as setas não estão funcionando em IOS. É preciso verificar para poder resolver esse problema.

**Comment by FranciscoSMM** [comment]
Mock up da versão mobile.

![image](https://user-images.githubusercontent.com/38992510/48861601-21f9a700-edab-11e8-9134-aff6bbf79d18.png)

**Comment by FranciscoSMM** [comment]
mock up da versão de desktop

![image](https://user-images.githubusercontent.com/38992510/48862193-b7496b00-edac-11e8-8cab-7231593b9ada.png)

**Comment by joaaogui** [comment]
A issue será continuada na issue #224
