### ISSUE TITLE
Refinar mapa de valor captado

### ISSUE THREAD

**Issue by joaaogui** [lappis-unb/PromovaCultura#226]
### Tarefas

- [x] Resolver posição/largura dos cards laterais
- [x] Repensar utilização do loader em toda a página
- [x] Adicionar máscara para valores. (Otimizar visualização nas linhas do mobile)
- [x] Com a possível adição da legenda das cores (como o mapa de calor) repensar se o total continua sticky.

### Critérios de Aceitação
- [x] O posicionamento das informações secundárias está otimizado para leitura e ocupação do espaço.

**Comment by guilacerda** [comment]
@FranciscoSMM você já tem disponível o mockup de como ficaria a posição e largura dos cards?

**Comment by guilacerda** [comment]
Comentário refere-se também a segunda task da issue #240 .

### Loader

* Ficou decidido que não utilizaríamos mais o loader rotatório para representar o carregamento de dados da API.

* Identificamos um padrão de loader que está sendo utilizado por grandes empresas (Youtube, Facebook, iFood e outros), que é o PlaceHolder.

* Primeiramente aplicamos em nossa visualização de desktop nos cards da legenda e nos cards do hover do mapa.

* Deixamos o mapa descolorido enquanto esperamos os dados carregarem.

* Foi utilizado o padrão de _disabled_ do bootstrap para deixar o botão inativo enquanto carrega os dados.

![image](https://user-images.githubusercontent.com/26297247/52206796-7cf75200-2862-11e9-9719-405fe3e6ae26.png)
