### ISSUE TITLE
Implementar filtros da ideia "Que bonitas as luzes"

### ISSUE THREAD

**Issue by eduardonunes2525** [lappis-unb/PromovaCultura#23]
Ver conclusão de #18

**Comment by rodmaia2099** [comment]
Redundância com [Criar filtros de interação com o mapa do Brasil](https://github.com/lappis-unb/promovacultura/issues/18)?

**Comment by rodmaia2099** [comment]
Issue editada para eliminar a redundância

**Comment by fabio1079** [comment]
Um exemplo com código:
  https://gist.github.com/serenatsay/1f14d98912ec5a597c02
  https://codepen.io/serenatsay/pen/EPgVXL

**Comment by rodmaia2099** [comment]
Vale a pena avaliarmos a possibilidade de criar um banco separado com as situações do projeto? Busca textual me parece meio arriscado. Se alguém mudar a string quebra a consulta. 

Também poderíamos fixar os códigos de situação (E90, etc) como parâmetros que passamos para a API, sem precisar adicionar mais uma etapa na consulta. 

Lembrando que é só um protótipo. Precisamos fazer a consulta funcionar, mas a solução não precisa ser elegante já que vamos refazer depois. 

Vale a pena conversar com o Luciano porque ele está trabalhando com as situações no Salic-ML

**Comment by marcosronaldo** [comment]
Pendencias mapeadas na issue #80

**Comment by marcosronaldo** [comment]
Filtros de situação sendo extraídos de um campo maior de texto de projeto.
