### ISSUE TITLE
Prototipar exibição das informações ao interagir com o mapa (Ideia #70)

### ISSUE THREAD

**Issue by eduardonunes2525** [lappis-unb/PromovaCultura#24]
[Ideia: #70]

- [x] Mostrar um tooltip com total? (ver #59)
- [x] Mostrar um card com detalhes? Quais? (ver #17)
- [x] O que muda dependendo do suporte (responsivo)?

------

### Critérios de aceitação
- [x] Detalhar pelo menos 3 alternativas
- [x] Documentar alternativas na issue
- [x] Validar alternativas com a equipe
- [x] Documentar feedback da equipe na issue

**Comment by rodmaia2099** [comment]
[Interação com os mapas.pdf](https://github.com/lappis-unb/PromovaCultura/files/2160189/Interacao.com.os.mapas.pdf)

**Comment by rodmaia2099** [comment]
Feedback do Peter e do Shiko:

Alternativa 2: Considerar um dropdown de região para acelerar a navegação entre UFs

Alternativa 3: Mostrar o pop-up desktop mais à esquerda, sem encobrir tanto o mapa.
