### ISSUE TITLE
Refatorar visual do mapa de valor captado

### ISSUE THREAD

**Issue by joaaogui** [lappis-unb/PromovaCultura#240]
### Description

Existem alguns detalhes a serem melhorados no mapa de valor captado

### Tasks

- [x] Valor na legenda deve ter o separador de milhar com virgula
- [x] Botão de exportar dados deve ficar visivel somente quando os dados estiverem disponivesis

**Comment by guilacerda** [comment]
Juntamente com a conclusão da task da issue #226 de repensar o loader, o botão de exportar csv foi padronizado para não funcionar antes dos dados da api carregarem.

**Comment by guilacerda** [comment]
Segue imagem do resultado do loader do botão (e do resto da visualização)

![image](https://user-images.githubusercontent.com/26297247/52206796-7cf75200-2862-11e9-9719-405fe3e6ae26.png)

**Comment by guilacerda** [comment]
Comentário referente também às alterações necessitadas na issue #226 e na #227.

Foram feitas algumas alterações na visualização do protótipo, as quais alteraram:

### Legenda das cores e Totais

* O card lateral da legenda era exibido em formato de aba, alteramos para que ficasse com título fixo e completo.

* Visto que não existia a necessidade de termos 6 intervalos no heatmap, diminuímos para 5.

* Foi também decidido que apresentaríamos apenas os números máximos dos valores captados dos intervalos da legenda. 

* Os títulos dos cards foram trocados e os valores centralizados

![image](https://user-images.githubusercontent.com/26297247/52209723-e62f9300-286b-11e9-9c4c-ad5bd2ea1e8f.png)
