### ISSUE TITLE
Prototipar uma visualização de relações CNPJ-CPF para a frente do ML

### ISSUE THREAD

**Issue by rodmaia2099** [lappis-unb/PromovaCultura#245]
### Descrição

A frente do ML está produzindo um grafo com relações de CNPJs de empresas e CPFs dos sócios para verificações da análise de resultado dos projetos submetidos na Lei Rouanet.

### Tarefas
- [ ] Verificar o formato dos dados gerados pela equipe do ML
- [ ] Definir ambiente de disponibilização dos dados
- [ ] Discutir requisitos dessa visualização dentro do contexto da frente do ML
- [ ] Prototipar versão inicial da visualização

### Critérios de aceitação
- [ ] O grafo mostra informações corretamente (de acordo com a versão inicial gerada pela equipe do ML)
- [ ] O grafo identifica relacionamentos problemáticos entre CPFs e CNPJs
- [ ] A visualização é acessível de fora do Lappis

**Comment by guilacerda** [comment]
O Promova Cultura foi dissolvido nas duas outras frentes de trabalho do LAPPIS (Taís e ML), portanto não utilizaremos mais o [repositório](https://github.com/lappis-unb/PromovaCultura) para a finalidade de documentação do trabalho futuro da ex-equipe do Promova. Os trabalhos realizados pela equipe serão documentados nos respectivos repositórios de trabalho na qual foram dissolvidos.
