### ISSUE TITLE
Prototipar uma visualização interativa para mostrar históricos de conversa da assistente virtual Tais

### ISSUE THREAD

**Issue by rodmaia2099** [lappis-unb/PromovaCultura#246]
### Descrição
A assistente virtual Tais já está em funcionamento e precisa complementar as ferramentas de analytics para mapear mensagens mais frequentes e sequências de mensagens mais comuns.

### Tarefas
- [ ] Verificar com a equipe do chatbot como os dados de histórico de conversa são armazenados
- [ ] Estudar ferramentas semelhantes (ex.: [Chatbase](https://chatbase.com/sessionflow?botKey=005f4c4c-e61a-4cd6-b60b-f23424881c79&platform=__any__&version=__any__&period=30&cohortsPeriod=6week)
- [ ] Prototipar possibilidades de interação (estático?)

### Critério de aceitação
- [ ] A visualização mostra intents mais frequentes
- [ ] A visualização mostra o "caminho" mais frequentemente seguido pelos usuários e os desdobramentos
- [ ] Temos alternativas de protótipo para discutir com a nossa equipe
- [ ] Podemos estivar o esforço de implementação da alternativa escolhida

**Comment by guilacerda** [comment]
O Promova Cultura foi dissolvido nas duas outras frentes de trabalho do LAPPIS (Taís e ML), portanto não utilizaremos mais o [repositório](https://github.com/lappis-unb/PromovaCultura) para a finalidade de documentação do trabalho futuro da ex-equipe do Promova. Os trabalhos realizados pela equipe será documentado nos respectivos repositórios de trabalho na qual foram dissolvidos.
