### ISSUE TITLE
Pesquisar efeitos visuais para exibição das informações [Ideia #72]

### ISSUE THREAD

**Issue by eduardonunes2525** [lappis-unb/PromovaCultura#26]
Pesquisar bibliotecas de animação e efeitos visuais que possam ser integradas com os mapas que já construímos.

Insipiração: http://www.visualcapitalist.com/interactive-mapping-flow-international-trade/

**Comment by marcosronaldo** [comment]
Particulas de fundo - MIT
https://vincentgarreau.com/particles.js/

Vários efeitos diferenciados em JS - MIT
http://soulwire.github.io/sketch.js/

botões com efeitos em particulas - (livre com referencia da fonte)
https://github.com/codrops/ParticleEffectsButtons/

Particulas de fundo - (licença individual por biblioteca/efeito)
https://www.cssscript.com/tag/particle-system/

Vários efeitos de partículas
https://bashooka.com/coding/particle-effect-animation-tutorials-examples/

Biblioteca para animar SVG - MIT
http://svgjs.com/getting-started/

Biblioteca para animar SVG - Apache2
http://snapsvg.io/start/
http://svg.dabbles.info/snaptut-load-animate
