### ISSUE TITLE
Implementar gráfico em forma funil com filtro para visualizações de quantidades de projeto

### ISSUE THREAD

**Issue by eduardonunes2525** [lappis-unb/PromovaCultura#27]
Gráfico representará as etapas do processo de avaliação de um projeto na lei Rouanet

* https://www.amcharts.com/demos/3d-funnel-chart/
* https://canvasjs.com/javascript-charts/funnel-chart/

O funil deve contemplar as seguintes etapas:
* Quantidade de propostas
* Quantidade de projetos
* Quantidade de projetos que captaram
* Quantidade de projetos executados

## Tarefas

- [x] Fazer funil reagir à mudanças no slider
- [x] Slider deve selecionar um range
- [x] Posicionar o slider e o gráfico de modo responsivo
- [x] Mostrar balões com os valores selecionados no slider
- [ ] Fazer funil mostrar dados reais a partir do BD/API

(Ver #74)

**Comment by joaaogui** [comment]
Bibliotecas com o topo sempre maior:
* https://github.com/jakezatecky/d3-funnel
* https://www.amcharts.com/demos/3d-funnel-chart/
* https://canvasjs.com/javascript-charts/funnel-chart/

**Comment by joaaogui** [comment]
Opção escolhida: https://github.com/YetiForceCompany/chartjs-plugin-funnel

**Comment by rodmaia2099** [comment]
O slider agora se posiciona de modo responsivo e mostra um balão com valores selecionados
