### ISSUE TITLE
Prototipar área com resumo sobre cada projeto

### ISSUE THREAD

**Issue by peterlima** [lappis-unb/PromovaCultura#38]

**Comment by peterlima** [comment]
Imagem destaque, título, resumo, informações básicas, badges "medalhas" e dados para contato.

**Comment by navarrovmn** [comment]
* Dados de projeto 
  * Título
  * Resumo
  * Área
  * Segmento
  * Município (do proponente)
  * Contato do proponente (endereço, telefone comercial, telefone residencial, fax, correio eletrônico, endereço de internet)
  * Situação e sua data
  * Data de início de execução 
  * UF
  * Deslocamento
  * Distribuição

**Comment by marcosronaldo** [comment]
Página de projeto retirada do escopo.
