### ISSUE TITLE
Definir cálculo do índice de impacto do projeto

### ISSUE THREAD

**Issue by rodmaia** [lappis-unb/PromovaCultura#48]
* [x] Levantar dimensões úteis
* [ ] Procurar referência de normalização de dados culturais
* [ ] Comparar variação das informações para cada enquadramento de projeto
* [x] Conversar com pessoal do ML

**Comment by rodmaia2099** [comment]
Coloquei um exemplo de formulário com linguagem natural no Surge, só pra demonstrar como funcionaria na prática: http://naturallangform.surge.sh. 
O código que usei como base está disponível aqui: https://tympanus.net/codrops/2013/05/21/natural-language-form-with-custom-input-elements/.

**Comment by rodmaia2099** [comment]
Sugestão de dimensões a considerar para o cálculo do índice:
- Quantidade de locais de realização _(fator multiplicador)_
- Quantidade de distribuição gratuita _(aumenta o índice)_
- Usou o máximo de preço popular (20%), desde que a distribuição não seja 100% gratuita? _(aumenta o índice)_

**Comment by rodmaia2099** [comment]
A conclusão atual é de que só podemos comparar o índice de propostas/projetos dentro da mesma categoria. Comparar projetos de bibliotecas com projetos de teatro geraria distorções no índice.

Por enquanto, vamos usar um índice "simulado" para implementar as visualizações. Assim que a frente de ML gerar um índice de saúde dos projetos usaremos estes dados.
