### ISSUE TITLE
Visualização dos projetos

### ISSUE THREAD

**Issue by RochaCarla** [lappis-unb/PromovaCultura#6]
- [ ] Modular

- [ ] Informações: 

- Parte automática
- Parte gerada pelo proponente

- [ ] Ver dados nos esboços

- [ ] Explocarar mais opções de arranjo das informações

**Comment by joaaogui** [comment]
![visualizacao](https://user-images.githubusercontent.com/11447904/38503669-0e86002a-3be9-11e8-9a07-791cd41d5bce.jpg)

**Comment by joaaogui** [comment]
![visualizacao 2](https://user-images.githubusercontent.com/11447904/38503681-13677de4-3be9-11e8-834c-b80ab0cafe55.jpg)

**Comment by joaaogui** [comment]
![visualizacao 4](https://user-images.githubusercontent.com/11447904/38503698-1eb0b72e-3be9-11e8-8ee0-aa56a0b06b34.jpg)

**Comment by rodmaia2099** [comment]
A épica e todas as issues associadas foram retiradas de escopo por mudanças no projeto
