### ISSUE TITLE
Prototipar formas efetivas de representar os dados no mapa

### ISSUE THREAD

**Issue by rodmaia2099** [lappis-unb/PromovaCultura#62]
* [x] Refazer Crazy 8s
* [x] Esboçar alternativas de representação
* [x] Fazer alternativas de protótipo de alto nível

**Comment by FranciscoSMM** [comment]
Crazy 8s do Francisco e do Rodrigo

![photo5181409397723736021](https://user-images.githubusercontent.com/38992510/40188554-95f32fe2-59d0-11e8-8a8e-1b218c409122.jpg)
![photo5181409397723736022](https://user-images.githubusercontent.com/38992510/40188571-9efefa26-59d0-11e8-9bdf-cd9105b23d6b.jpg)

**Comment by peterlima** [comment]
Crazy 8s do Peter

![crazy8s](https://user-images.githubusercontent.com/7669922/40193091-a6968c16-59dc-11e8-8e90-d622190b184c.jpg)

**Comment by eduardonunes2525** [comment]
![photo5184115480523286475](https://user-images.githubusercontent.com/13136988/40195091-db277426-59e2-11e8-97ea-b1e7d9cd154d.jpg)

**Comment by marcosronaldo** [comment]
![photo5183807909325285340](https://user-images.githubusercontent.com/2592217/40195297-81b33000-59e3-11e8-9f82-daca3f26257c.jpg)
![photo5181775956002580533](https://user-images.githubusercontent.com/2592217/40195309-8cc0f7fc-59e3-11e8-9624-c93c851fae50.jpg)

**Comment by marcosronaldo** [comment]
Resumo: 
* 5 Mapa de Calor (1 tipo informação)
* 3 Ícones no mapa representando resultado da pesquisa. Icones maiores ou menores
* 2 Mapa de Calor (mais tipos de informação, com texturas diferentes por região por exemplo)
* 2 Ícones/luzes no mapa representando resultado da pesquisa. Icones em maior quantidade
* 2 Preencher estado/região a partir da borda
* 2 Mostrar pins/tooltips com informações dentro do mapa. Números absolutos ou porcentagens
* 1 Elevação de perspectiva do estado/região. (3d)
* 1 Balões com informação por região (balão fora do mapa)
* 1 Camadas em perspectiva com informação distinta por camada
* 1 Mapa arame (só estados com informação aparecem coloridos)
* 1 Balões com círculo de porcentagens
* 1 Expandir região, e mostrar informações fora do mapa quando clicar nos estados
* 1 Selecionar estado/regiao e mostrar informações de forma externa
* 1 Mostrar informações sem o mapa. Selecionar região num dropdown, mostrar informações sem localização geografica
* 1 Mostrar ícones no mapa e integarir com ícone para mostrar mais informações
* 1 Comparação de informações de estados com multiselect
* 1 Ranking de estados disponibilizado no mapa com utilização de cores diferentes
* 1 Estados variam em tamanho de acordo com a informação. Manter ou não a forma do estado
* 1 Hover no mapa com informação da posição do cursor
* 1 Mudar o cursor para mostrar informação COM o cursor
* 1 Separar e reposicionar estados para mostrar informação
* 1 mancha de camera infravermelho, sem separacao de estados.
* 1 ampliar estado sobre o mapa e mostrar informacoes da silhueta no mapa

**Comment by FranciscoSMM** [comment]
Teste de visualização de informação pela densidade da co escolhida a partir da borda -  Região
![bordermap_test](https://user-images.githubusercontent.com/38992510/40612667-eda52180-6251-11e8-8ba4-3d5a7ff08de8.png)

Teste de visualização de informação pela densidade da co escolhida a partir da borda -  Estado
![iconmap_test_3](https://user-images.githubusercontent.com/38992510/40612670-ee0e5b0a-6251-11e8-9555-0936777ec22c.png)

Teste de visualização de volume de informação por mapa de calor monocromático.
![celtest4](https://user-images.githubusercontent.com/38992510/40612668-edca159e-6251-11e8-892e-ac0c2ade9566.png)

Teste de vizualização de imagens por tamanho de ícone que representa o que foi procurado
![iconmap_test](https://user-images.githubusercontent.com/38992510/40612669-edeba5a6-6251-11e8-951d-34898a99abdd.png)

Teste de visualização de informação por quantidade de pins em determinada região.
![iconmap_test_many_2](https://user-images.githubusercontent.com/38992510/40612672-ee301722-6251-11e8-9397-259ebc2289ac.png)

Teste de visualização de informação por quantidade de pins em determinado estado.
![iconmap_test_many_4](https://user-images.githubusercontent.com/38992510/40612673-ee4ea6e2-6251-11e8-8cdb-5d02e32b9910.png)

Vizualização da informação por números indicando o valor dentro da região
![numbermap_test_1_1](https://user-images.githubusercontent.com/38992510/40612675-ee6f9546-6251-11e8-82b8-91274acfef43.png)

Vizualização da informação por números indicando o valor dentro do estado.
![numbermap_test_5](https://user-images.githubusercontent.com/38992510/40612676-ee901b40-6251-11e8-98aa-92e4c7b7fa5f.png)

**Comment by rodmaia2099** [comment]
As alternativas 1 e 2 funcionariam melhor com um fundo monocromático e de alto contraste. Não devem ser priorizadas.

Na alternativa 4, indicar regiões pela sigla oficial. Norte -> N e Sul -> S.

Nas alternativas 5 e 6, os pins podem variar de tamanho.

Nas alternativas 7 e 8, podemos usar linhas para posicionar os números relativos à UFs pequenas (ex.: Sergipe e DF)

**Comment by FranciscoSMM** [comment]
Mapas de calor com várias informações. O problema é que seria preciso criar uma paleta de cores específicas que teria de ser relacionadas com as informações que nós ainda não temos, além de que em estados pequenos isso não seria visível de nenhuma foirma.
![mapafeio2](https://user-images.githubusercontent.com/38992510/40619067-06c5fee2-626a-11e8-965a-ad997a9b31df.png)
![mapafeio3](https://user-images.githubusercontent.com/38992510/40619068-06ebe76a-626a-11e8-8566-20b8aafd1051.png)
![mapafeio](https://user-images.githubusercontent.com/38992510/40619069-0710d9a8-626a-11e8-9863-4e23c3a841a2.png)
