### ISSUE TITLE
Componentizar protótipos gerados na sprint 1

### ISSUE THREAD

**Issue by rodmaia2099** [lappis-unb/PromovaCultura#63]
* [ ] Documentar experiência do uso do framework na Sprint

**Comment by marcosronaldo** [comment]
[Página na wiki](https://github.com/lappis-unb/PromovaCultura/wiki/An%C3%A1lise-da-prototipa%C3%A7%C3%A3o-em-c%C3%B3digo-utilizando-framework-javascript-de-componetiza%C3%A7%C3%A3o)

**Comment by marcosronaldo** [comment]
Faremos uso de protótipos como componentes vue quando virmos  a necessidade de reutilizar algum protótipo específico.
