### ISSUE TITLE
Home

### ISSUE THREAD

**Issue by joaaogui** [lappis-unb/PromovaCultura#7]
* TODO

**Comment by joaaogui** [comment]
![p_20180409_111517_vhdr_auto](https://user-images.githubusercontent.com/11447904/38503849-89515188-3be9-11e8-837a-51d713cda2e2.jpg)

**Comment by joaaogui** [comment]
![p_20180409_111522_vhdr_auto](https://user-images.githubusercontent.com/11447904/38503860-8f8718d0-3be9-11e8-873e-3b6668ad19b4.jpg)

**Comment by rodmaia2099** [comment]
A épica e todas as issues foram retiradas de escopo por mudanças no projeto
