### ISSUE TITLE
Implementar controles para o mapa (Ideia #70)

### ISSUE THREAD

**Issue by rodmaia2099** [lappis-unb/PromovaCultura#71]
[IDEIA: #70]

Terceiro quadro da ideia da design sprint.

- [x] Filtrar por tipo (segmento) de projeto ou por "todos"
- [x] Mostrar proponentes (liga-desliga) por filtro de segmento
- [x] Mostrar incentivadores (liga-desliga) por filtro de segmento

**Comment by fabio1079** [comment]
Este certo ?
![](https://user-images.githubusercontent.com/2592217/38994768-abf79aae-43bd-11e8-9729-bad0a2ecf08a.jpg)

**Comment by rodmaia2099** [comment]
Esse mesmo. Na dúvida basta olhar a lista de depenências da issue 😉

**Comment by fabio1079** [comment]
* No filtro mobile quando um segmento é selecionado, o valor está sendo mostrado em dobro no modal.
* Subir no github.pages
