### ISSUE TITLE
Melhorar apresentação visual do funil (Ideia #10)

### ISSUE THREAD

**Issue by rodmaia2099** [lappis-unb/PromovaCultura#74]
- [x] Mostrar limites da escala do slider (1 e 10)
- [x] Melhorar posicionamento dos elementos em breakpoints > MD
- [x] Acrescentar título "Saúde do projeto" ao slider
- [x] Mostrar quantidades projetos de cada etapa dentro do funil
- [x] Identificar cada fatia do funil com o nome correspondente
- [x] Melhorar visual do funil (cores e tipografia)

------

## Critérios de aceitação
* [x]  Os **limites da escala** do slider estão claramente visíveis tanto no desktop quanto no mobile.
* [x] Todos os **elementos na tela estão balanceados** visualmente, fáceis de ler e acessar. Tanto no desktop quanto no mobile.
* [x] O slider tem um **título visível** ("Saúde do projeto") tanto no desktop quanto no mobile.
* [x] As **quantidades de projetos e os nomes das etapas** estão claramente visíveis dentro de cada fatia. Tanto no desktop quanto no mobile.
* [x] O funil tem um **visual agradável**.
* [x] Verifiquei que funciona tanto no **desktop quanto no celular**
* [x] **Teste manual** realizado (testei que funciona e não quebrou nada do que já estava feito)
* [x] Confirmei que o **Merge request** foi revisado e aceito por uma pessoa que não estava envolvida na issue
* [x] Documentei as **exceções aos objetivos** da issue ou aos critérios de aceitação em um **comentário na issue**.
* [x] Documentei **todos os bugs** encontrados em novas issues, explicando o problema e os passos para reproduzir.

**Comment by peterlima** [comment]
Proposta visual do funil

![proposta_visual_funil](https://user-images.githubusercontent.com/7669922/43076701-6982219c-8e5b-11e8-9417-8642fbdfef90.png)

**Comment by peterlima** [comment]
**Opções de cores para o funil**

![proposta_visual_funil](https://user-images.githubusercontent.com/7669922/43089994-8a6f794c-8e7c-11e8-9ade-e9c0648680b5.png)

**Comment by peterlima** [comment]
Arquivo fonte - Cores 
[cores_funil.zip](https://github.com/lappis-unb/PromovaCultura/files/2220228/cores_funil.zip)
Funil (.ai)

**Comment by fabio1079** [comment]
Para deixar a font em bold nos valores do funil, foi necessário clonar a biblioteca [chartjs-plugin-datalabels](https://github.com/chartjs/chartjs-plugin-datalabels) e fazer alterações no código fonte dela.

Arquivo labels.js, função drawText. 
```javascript
        ...
        var oldCtxFont = ctx.font;
	var fontWithBold = oldCtxFont.split('px');

	fontWithBold.shift(); // remove the px value
	fontWithBold = ['bold', '28px'].concat(fontWithBold).join(' ');

	for (i = 0; i < ilen; ++i) {
		if (i === 0) {
			ctx.font = fontWithBold;
		} else {
			ctx.font = oldCtxFont;
		}
        ...
```
Tal alteração foi feita pois a biblioteca não permite a adição de HTML, apenas texto puro e não podemos alterar o estilo da forma como desejamos.

Para reproduzir basta:
1 - Clonar o repositório https://github.com/chartjs/chartjs-plugin-datalabels
2 - Ir para o commit ab410dd1b38b8791451731715980d50c7b44e9ff
3 - Adicionar o código acima e executar a build deste: npm install && ./node_modules/.bin/gulp build
4 - Copiar o arquivo _dist/chartjs-plugin-datalabels.js_ para a pasta _PromovaCultura/gh-pages/funil/js_

![funil](https://user-images.githubusercontent.com/4295523/43095092-127fccde-8e8b-11e8-94d4-c7466bad67fe.png)

**Comment by fabio1079** [comment]
Encontrei uma forma melhor na qual podemos customizar pelo html na tag canvas usando [data attributes](https://developer.mozilla.org/en-US/docs/Learn/HTML/Howto/Use_data_attributes).

Na biblioteca(chartjs-plugin-datalabels/src/label.js, função drawText)
```javascript
...
  var valueFont = ctx.canvas.dataset.value || ctx.font;
  var labelFont = ctx.canvas.dataset.label || ctx.font;

  for (i = 0; i < ilen; ++i) {
    if (i === 0) {
      ctx.font = valueFont;
    } else {
      ctx.font = labelFont;
    }
...
```

No nosso HTML:
```html
<canvas
  id="myChart"
  height="300"
  data-value='600 28px "Helvetica Neue", "Helvetica", "Arial", sans-serif'
  data-label='500 15px "Helvetica Neue", "Helvetica", "Arial", sans-serif'
></canvas>
```

Assim compilamos apenas uma vez a biblioteca e sempre que quisermos fazer mudanças no estilo é só mudar _data-value_ e _data-label_ no html.

**Comment by fabio1079** [comment]
Aumentei a distancia entre o valor e o texto e pra não ter que ficar refazendo sempre essas mudanças no código deles, fix um fork com as nossas mudanças: https://github.com/lappis-unb/chartjs-plugin-datalabels/commits/multline_label_settings

**Comment by navarrovmn** [comment]
Bug observado: se você mudar os valores no slider sem usar as bolinhas (clicar, por exemplo, em no 4), nada acontece no funil.

Há duas abordagens possíveis:
- Fazer funcionar com os dois "tipos" de arrastar
- Não permitir que o slider mude a não ser pela bolinha

**Comment by eduardonunes2525** [comment]
Não foi implementado a versão com o slider na posição vertical.
