### ISSUE TITLE
Mostrar quantidade de proponentes e incentivadores junto ao funil [Ideia #10]

### ISSUE THREAD

**Issue by rodmaia2099** [lappis-unb/PromovaCultura#75]
[Ideia: #10]

- [x] Avaliar se devemos mostrar porcentagens de proponentes e incentivadores ou se devemos mostrar apenas valores absolutos
- [x] Mostrar ícones representando a quantidade de proponentes
- [x] Mostrar ícones representando a quantidade de incentivadores
- [x] Atualizar filtros para controlar a exibição dos ícones 

------

## Critérios de aceitação
* [x]  **Quantidade de proponentes** relacionados às propostas dentro do range selecionado está sempre visíveis.
* [x]  **Quantidade de incentivadores** relacionados às propostas dentro do range selecionado está sempre visíveis.
* [x] Quantidade de proponentes e incentivadores varia de acordo com a mudança no range.
* [x] Verifiquei que funciona tanto no **desktop quanto no celular**
* [x] **Teste manual** realizado (testei que funciona e não quebrou nada do que já estava feito)
* [x] Confirmei que o **Merge request** foi revisado e aceito por uma pessoa que não estava envolvida na issue
* [x] Documentei as **exceções aos objetivos** da issue ou aos critérios de aceitação em um **comentário na issue**.
* [x] Documentei **todos os bugs** encontrados em novas issues, explicando o problema e os passos para reproduzir.

**Comment by peterlima** [comment]
Proposta visual para interface do funil

![proposta-visual-interface-funil](https://user-images.githubusercontent.com/7669922/43076653-47923c20-8e5b-11e8-9260-e8212eb8a4c2.png)

**Comment by peterlima** [comment]
Proposta visual para interface do funil

![proposta-visual-interface-funil](https://user-images.githubusercontent.com/7669922/43076969-6bfe0624-8e5c-11e8-9471-e55c3008491b.png)

**Comment by peterlima** [comment]
**Proposta visual - Interface funil**

![funil_range_horizontal](https://user-images.githubusercontent.com/7669922/43089857-27886bfe-8e7c-11e8-96cf-15b2bfa0a6f7.png)

![funil_range_horizontal_card](https://user-images.githubusercontent.com/7669922/43089939-622ce91a-8e7c-11e8-9fe2-f9e662c5841c.png)

![funil_range_vertical](https://user-images.githubusercontent.com/7669922/43089942-65fd3afe-8e7c-11e8-8426-a556267ac9a4.png)

**Comment by peterlima** [comment]
**Arquivo fonte - Interface Funil (.ai)**

[proposta_visual_interface_funil.zip](https://github.com/lappis-unb/PromovaCultura/files/2220224/proposta_visual_interface_funil.zip)

**Comment by eduardonunes2525** [comment]
Em relação a porcentagem, foi utilizado o recurso visual de uma barra de progresso ao invés de um número indicando a porcentagem real dos valores equivalentes.
