### ISSUE TITLE
Rankings da cultura

### ISSUE THREAD

**Issue by rodmaia2099** [lappis-unb/PromovaCultura#76]
Mostra um ranking das UFs com mais projetos de um determinado tipo e a distribuição desses resultados no mapa.

![photo5100782923023493060](https://user-images.githubusercontent.com/2592217/38995454-465ae1e0-43bf-11e8-91ff-99bd3fa40b66.jpg)

**Comment by navarrovmn** [comment]
Nos dois primeiros quadros, são representados a visualizações por número de ícones no mapa. O dropdown seria pra representar a área que você tá pesquisando (como por exemplo, música, filme ou mesmo dinheiro investido) e o número de ícones em cada estado seria o indicativo da diferença de investimento desse estado em relação aos outros. A tabela ao lado é apenas para tornar essa visualização mais precisa.

O último quadro trata-se de escolher uma área e ver quais áreas de produção estão investindo mais nela. Por exemplo, se a indústria agropecuária fomenta mais a música do que a indústria de eletrônicos, por exemplo.

**Comment by rodmaia2099** [comment]
Mudanças no projeto tornaram essa issue dispensável
