### ISSUE TITLE
Referências

### ISSUE THREAD

**Issue by RochaCarla** [lappis-unb/PromovaCultura#8]
- [ ] Repositório de dados, BI, e opensource (Projeto Media Lab)
http://dataviva.info/pt/

- [ ] https://www.media.mit.edu/groups/collective-learning/overview/

- [ ] https://datausa.io/

**Comment by navarrovmn** [comment]
* [ ] https://www.nytimes.com/interactive/2014/upshot/buy-rent-calculator.html?_r=0
* [ ] http://www.visualcapitalist.com/interactive-mapping-flow-international-trade/
* [ ] https://www.mapd.com/demos/tweetmap/
* [ ] http://www.bbc.com/future/story/20120821-how-many-alien-worlds-exist
* [ ] https://www.mapd.com/demos/tweetmap/
* [ ] http://www.bizbrain.org/coffee/
* [ ] https://www.behance.net/gallery/25428901/WIRED-UK-How-Data-Saved-Music
* [ ] https://adminlte.io/themes/AdminLTE/index2.html
* [ ] https://github.com/DataUSA

**Comment by peterlima** [comment]
- https://colorlib.com/polygon/adminator/index.html
- https://colorlib.com/polygon/sufee/index.html
- https://colorlib.com/polygon/gentelella/index.html
- http://ui-patterns.com/users/7459/collections/search-and-filter_1/screenshots/12627
- https://www.data.gov/
- http://govdata.gov.br/plataforma.html

**Comment by rodmaia2099** [comment]
- [ ] http://www.atlaspolitico.com.br
- [ ] http://radarparlamentar.polignu.org/plenaria/sen/PLS-00098-2002
- [ ] https://www.flightradar24.com
