### ISSUE TITLE
Evolução de filtros na API salic para filtragem com linguagem natural [Ideia #72]

### ISSUE THREAD

**Issue by marcosronaldo** [lappis-unb/PromovaCultura#80]
[Ideia #72]

* [ ] Filtros de datas
* [ ] Locais corretos de incentivadores
* [ ] Incluir os locais dos deslocamento de projetos
* [x] Lista da quantidade de projetos por estado
* [ ] Quantidade de projetos por ano

**Comment by rodmaia2099** [comment]
Precisamos discutir a complexidade de implementar cada uma dessas dimensões e decidir se vamos mantê-las, esperando ajuda da frente do SALIC-ML ou se nós vamos removê-las e redesenhar os filtros.

**Comment by marcosronaldo** [comment]
O filtro de linguagem natural está filtrando por área e situação apenas, e além disso está fazendo isso com apenas 100 projetos, pois buscar com todos da forma implementada seria impraticável. Para fazer essa contagem com dados reais para todos os projetos com velocidade aceitável, precisamos criar um endpoint específico para isso dentro da API salic, ou evoluir algum endpoint existente. Assim, nenhum dos dados buscados nos protótipos desenvolvidos até agora são suficientes para implementar de fato esse filtro.

**Comment by marcosronaldo** [comment]
Precisamos que o endpoint já implementado de contagem de proetos na API salic, utilizado nos prototipos de mapa, filtre os restultados por:
* Local mostrado (ainda será por UF/Regiao):
  * Da proposta/do proponente;
  * Onde o projeto foi/será executado;
  * De onde veio incentivo para esses projetos;
  * Onde estão os fornecedores desses projetos

* Diferenciar projetos/propostas

* área

* Estado do projeto (executado, cancelado, em fase de admissao, de coleta)

* data do projeto (por ano? data especifica? range de datas?)

**Comment by rodmaia2099** [comment]
Fechando a issue por mudanças de direcionamento no projeto
