### ISSUE TITLE
Implementar fonte de dados para proponentes e incentivadores por UF/Regiao

### ISSUE THREAD

**Issue by marcosronaldo** [lappis-unb/PromovaCultura#81]
- [ ] Filtrar por tipo (segmento) de projeto ou por "todos"
- [ ] Retornar quantidade de proponentes por UF/Regiao (dado algum filtro X de projeto)
- [ ] Retornar quantidade de incentivadores por UF/Regiao (dado algum filtro X de projeto)

Ex de resposta esperada:
```code
{
  "DF": 21,
  "ES": 65
}
```

**Comment by joaaogui** [comment]
Problema encontrado ao buscar por incentivadores: Quando se dá join da tabela de interessado com pre-projeto, o numero de incentivadores é retornado incorretamento. Motivo deconhecido.

O join foi retirado já que nao seria necessário utilizar nenhuma informaçã ode preprojeto para filtrar incentivadores

**Comment by fabio1079** [comment]
* A contagem de incentivadores não pode ser usada pelo versalic.
* Devido a complexidade dos dados, não foram feitos testes.
