### ISSUE TITLE
Mapa

### ISSUE THREAD

**Issue by marcosronaldo** [lappis-unb/PromovaCultura#9]
Visualização geográfica das informações culturais, com diferentes formas de apresentação.
* Mapa com animações.
* Mapa simples dos projetos com filtragem rápida de dados.
* Panorama com cards de trunfo e linha do tempo.
* Ranking com ícones e áreas da indústria.

**Comment by marcosronaldo** [comment]
![photo5100782923023493061](https://user-images.githubusercontent.com/2592217/38994726-8a5c06be-43bd-11e8-944c-75046908f8c3.jpg)

**Comment by marcosronaldo** [comment]
![photo5100782923023493062](https://user-images.githubusercontent.com/2592217/38994755-a2a9a078-43bd-11e8-830e-0099587a46b2.jpg)

**Comment by marcosronaldo** [comment]
![photo5100782923023493061](https://user-images.githubusercontent.com/2592217/38994768-abf79aae-43bd-11e8-9729-bad0a2ecf08a.jpg)

**Comment by marcosronaldo** [comment]
![photo5100782923023493064](https://user-images.githubusercontent.com/2592217/38995420-352becf2-43bf-11e8-92f1-e7da838daa2f.jpg)

**Comment by marcosronaldo** [comment]
![photo5100782923023493060](https://user-images.githubusercontent.com/2592217/38995454-465ae1e0-43bf-11e8-91ff-99bd3fa40b66.jpg)

**Comment by rodmaia2099** [comment]
Fechando a issue por mudanças de direcionamento no projeto
