### ISSUE TITLE
Implementar legendas para o mapa (Ideia: #70)

### ISSUE THREAD

**Issue by rodmaia2099** [lappis-unb/PromovaCultura#90]
[Ideia: #70]

- [x] Prototipar exibição das legendas na tela (responsivo)
- [x] Implementar a exibição dos valores das legendas (escala) com base nos filtros
- [ ] Mostrar legendas dos proponentes somente se esse filtro estiver ativo
- [ ] Mostrar legendas dos incentivadores somente se esse filtro estiver ativo

**Comment by FranciscoSMM** [comment]
os ícones precisaram ser re exportados devido a um erro no tamanho do documento
[Icones_escalados.zip](https://github.com/lappis-unb/PromovaCultura/files/2103590/Icones_escalados.zip)

**Comment by rodmaia2099** [comment]
"Mostrar legendas dos proponentes somente se esse filtro estiver ativo" e "Mostrar legendas dos incentivadores somente se esse filtro estiver ativo" não foram completadas nessa issue.
Foram mapeadas em #98
