### ISSUE TITLE
Reorganizar GitHub page do PromovaCultura [Ideia #70]

### ISSUE THREAD

**Issue by rodmaia2099** [lappis-unb/PromovaCultura#91]
> [Ideia #70]

Reorganizar apresentação da GitHub page do PromovaCultura para listar de forma clara todos os protótipos criados. 

A página deve permitir que qualquer pessoa veja o resultado do trabalho realizado. Deve ser responsiva.

Verificar a viabilidade de utilizar uma integração entre a index.html e a index do vuejs.
Utilizar uma index apenas do vuejs.
Definir o layout da home.
Estudar o uso de miniaturas das ideias.

-------

## Critérios de aceitação
* [x] **Qualquer pessoa** pode acessar todos protótipos do PromovaCultura no endereço https://lappis-unb.github.io/PromovaCultura/
* [x] Todos os protótipos listados na página estão **funcionando da mesma forma que estavam fora do Github pages**
* [x] Qualquer membro do Lappis consegue **entender o que o PromovaCultura realizou** apenas visitando a lista de protótipos (página inicial de https://lappis-unb.github.io/PromovaCultura/)
* [x] A lista de protótipos funciona tanto no **desktop quanto no celular** 
* [x] Qualquer membro do PromovaCultura consegue **atualizar a lista de protótipos**
* [x] **Teste manual** realizado (testei que funciona e não quebrou nada do que já estava feito)
* [x] Arquivos **commitados na master**
* [x] As exceções aos objetivos da issue ou aos critérios de aceitação foram documentadas em um **comentário na issue**

**Comment by joaaogui** [comment]
Tutorial de como se faz o deploy está em [Deploy-no-github-pages]

**Comment by rodmaia2099** [comment]
Bugs na index foram documentados em #124
