### ISSUE TITLE
Corrigir exibição dos Pins no mapa (Idea #70)

### ISSUE THREAD

**Issue by rodmaia2099** [lappis-unb/PromovaCultura#92]
[Ideia: #70]

* [x] Refazer SVGs dos pins para que todos tenham o mesmo tamanho
* [x] Simplificar os ícones dos pins
* [ ] Testar formas melhores de posicionar os pins no mapa

**Comment by marcosronaldo** [comment]
ícones na #93

**Comment by rodmaia2099** [comment]
Tarefa "Testar formas melhores de posicionar os pins no mapa" não foi completada nessa issue.
Foi mapeada em #106.
