### ISSUE TITLE
Atualizar exibição de pins de Proponentes e Incentivadores quando o segmento muda (Idea #70)

### ISSUE THREAD

**Issue by rodmaia2099** [lappis-unb/PromovaCultura#93]
[Ideia: #70]

Os pins de Proponentes e Incentivadores não atualizam quando o segmento é alterado nos filtros.

Etapas para reproduzir:

* Abrir mapa (mostra todos os segmentos por padrão)
* Ativar filtro de Proponentes
* Ativar filtro de Incentivadores
* Alterar segmento para "Teatro"
* Notar que os pins não mudaram

**Comment by FranciscoSMM** [comment]
ícones atualizados
[new_new_icons.zip](https://github.com/lappis-unb/PromovaCultura/files/2125159/new_new_icons.zip)

**Comment by rodmaia2099** [comment]
Resolvido no esforço de componentização dos elementos, relacionado à #85
