### ISSUE TITLE
Filtro de segmento funciona somente no mapa de UF, deve funcionar no mapa de Região [Ideia #70]

### ISSUE THREAD

**Issue by joaaogui** [lappis-unb/PromovaCultura#96]
> [Ideia #70]
> Relacionada à #85

## Etapas para reproduzir:
* Abrir mapa de calor por região
* Alterar segmento nos filtros
* Notar que o mapa não atualiza

-------

## Critérios de aceitação
* [x] **Mapa de calor** atualiza quando o segmento é alterado
* [x] Pins de **proponente** atualizam quando o segmento é alterado
* [x] Pins de **incentivador** atualizam quando o segmento é alterado
* [x] **Teste manual** realizado (testei que funciona e não quebrou nada no mapa de região)
* [x] Arquivos **commitados na master**
* [x] Solução disponível no **GitHub pages** (ou em um ambiente local, caso #91 não esteja pronto)
* [x] As exceções aos objetivos da issue ou aos critérios de aceitação foram documentadas em um **comentário na issue**

**Comment by fabio1079** [comment]
Quando se passa de um segmento que possui pins, para um que não tem e volto para um tem, os pins não  atualizam.
EX:
1 - Dança
2 - Ópera Rock
3 - Teatro.

Os pins não aprecem do passo 2 para o 3.

Mas se troco entre segmentos que tem pins, eles atualizam normalmente.

**Comment by rodmaia2099** [comment]
Bug na exibição do segmento "Todos" documentado em #123.
