### ISSUE TITLE
Legendas por proponentes e incentivadores estão sempre visíveis [Ideia #70]

### ISSUE THREAD

**Issue by joaaogui** [lappis-unb/PromovaCultura#98]
> [Ideia #70]

As legendas devem aparecer somente quando os filtros estão ativados.

Atenção à legenda horizontal que precisa melhorar o layout quando proponentes e incentivadores estão invisíveis.

Tratar legenda com abas para evitar de mostrar uma única aba quando proponentes e incentivadores estão invisíveis.

-------

## Critérios de aceitação
* [x] Legenda de **proponentes** não aparece ao carregar a página, para cada uma das 6 versões de legenda
* [x] Legenda de **incentivadores** não aparece ao carregar a página, para cada uma das 6 versões de legenda
* [x] Legenda de **proponentes**  aparece ao ativar o filtro respectivo, para cada uma das 6 versões de legenda
* [x] Legenda de **incentivadores**  aparece ao ativar o filtro respectivo, para cada uma das 6 versões de legenda
* [x] **Teste manual** realizado (testei que funciona e não quebrou nada no mapa ou nas legendas)
* [x] Arquivos **commitados na master**
* [x] Solução disponível no **GitHub pages** (ou em um ambiente local, caso #91 não esteja pronto)
* [x] As exceções aos objetivos da issue ou aos critérios de aceitação foram documentadas em um **comentário na issue**

**Comment by marcosronaldo** [comment]
Melhoria: A legenda horizontal fica com espaço vazio nas colunas que estão desabilitadas (Proponentes e Incentivadores)

**Comment by eduardonunes2525** [comment]
__Bug conhecido__: Nas abas que indicam a categoria da legenda, se uma determinada aba estiver selecionada, e retirar a visualização da informação da aba da legenda atual (nos filtros). Ela não exibe 
a informação das legendas, só quando há a seleção de outra legenda.

**Comment by rodmaia2099** [comment]
Documentado em #125
