### ISSUE TITLE
Novos ícones ainda estão com texto [Ideia #70]

### ISSUE THREAD

**Issue by joaaogui** [lappis-unb/PromovaCultura#99]
>[Ideia #70]

Transformar $ e qualquer outro texto em curvas no SVG

-------

## Critérios de aceitação
* [x] Um "find $" no código fonte dos SVGs retorna zero resultado.
* [x] Pins de **proponente** foram atualizados em todos os componentes
* [x] Pins de **incentivador** foram atualizados em todos os componentes
* [x] Ícones corrigidos aparecem no browser de qualquer um dos engenheiros da equipe
* [x] **Teste manual** realizado (testei que funciona e não quebrou a visualização de nenhum mapa)
* [x] Arquivos **commitados na master**
* [x] Solução disponível no **GitHub pages** (ou em um ambiente local, caso #91 não esteja pronto)
* [x] As exceções aos objetivos da issue ou aos critérios de aceitação foram documentadas em um **comentário na issue**

**Comment by FranciscoSMM** [comment]
O erro era que os ícones com a seta branca haviam sido feitos a partir de uma versão antigas por acidente, mas as fontes foram transformadas em paths.
[2018_06_26_ICONS.zip](https://github.com/lappis-unb/PromovaCultura/files/2145076/2018_06_26_ICONS.zip)

**Comment by FranciscoSMM** [comment]
Descobrimos um problema com a proporção dos pins no mapa. Na legenda eles são colocados através do CSS, então o tamanho é controlado mais facilmente, mas pelo JSMaps a proporção não está sendo controlada facilmente e isso complica a modificação deles. Esse problema deverá ser adereçado em alguma sprint futura devido a sua dificuldade mais alta.

**Comment by FranciscoSMM** [comment]
apesar dos erros com o git, estou colcando aqui os ícones.
[icons_17_07_2018.zip](https://github.com/lappis-unb/PromovaCultura/files/2198763/icons_17_07_2018.zip)
